"use client";

import Link from "next/link";
import { useRouter, useSearchParams } from "next/navigation";
import { useEffect, useState, type FormEvent } from "react";
import { AppShell } from "../dashboard/app-shell";
import { useI18n } from "../i18n/i18n-provider";
import { housekeepingMessages, requestMessages } from "../../lib/i18n/dictionaries";

import { BrandLoader } from "../ui/brand-loader";

type Option = { id: string; name: string | null };
type Values = { number: string; name: string; categoryId: string; floorId: string; roomChecks: string[]; arrivalChecks: string[] };
const empty: Values = { number: "", name: "", categoryId: "", floorId: "", roomChecks: [], arrivalChecks: [] };

function Checklist({ label, values, placeholder, onChange }: { label: string; values: string[]; placeholder: string; onChange: (values: string[]) => void }) {
  const [draft, setDraft] = useState("");
  function add() { const value = draft.trim(); if (value) { onChange([...values, value]); setDraft(""); } }
  return <fieldset><legend className="mb-1.5 text-[12px] font-semibold text-[var(--qf-text-muted)]">{label}</legend><div className="space-y-2">{values.map((value, index) => <div key={`${value}-${index}`} className="flex gap-2"><input className="qf-field" value={value} onChange={(event) => onChange(values.map((item, itemIndex) => itemIndex === index ? event.target.value : item))} /><button type="button" onClick={() => onChange(values.filter((_, itemIndex) => itemIndex !== index))} className="flex h-[38px] w-[38px] shrink-0 items-center justify-center rounded-[7px] border border-red-500 text-[20px] font-semibold text-red-600 transition-[border-width] hover:border-[3px] focus-visible:border-[3px]">×</button></div>)}<div className="flex gap-2"><input className="qf-field" value={draft} placeholder={placeholder} onChange={(event) => setDraft(event.target.value)} onKeyDown={(event) => { if (event.key === "Enter") { event.preventDefault(); add(); } }} /><button type="button" onClick={add} className="flex h-[38px] w-[38px] shrink-0 items-center justify-center rounded-[7px] border border-[var(--qf-accent)] bg-[var(--qf-accent)] text-[20px] font-semibold text-white transition-[border-width] hover:border-[3px] hover:border-[var(--qf-accent-hover)] focus-visible:border-[3px]">+</button></div></div></fieldset>;
}

export function RoomEditor() {
  const { locale } = useI18n(); const t = housekeepingMessages[locale]; const router = useRouter(); const id = useSearchParams().get("edit");
  const [values, setValues] = useState<Values>(empty); const [categories, setCategories] = useState<Option[]>([]); const [floors, setFloors] = useState<Option[]>([]); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [error, setError] = useState("");
  useEffect(() => { let active = true; Promise.all([fetch(`/api/housekeeping/rooms?form=1&locale=${locale}`, { cache: "no-store" }).then(async (response) => { if (!response.ok) throw new Error("Unable to load room options."); return response.json() as Promise<{ categories: Option[]; floors: Option[] }>; }), id ? fetch(`/api/housekeeping/rooms/${id}?locale=${locale}`, { cache: "no-store" }).then(async (response) => { if (!response.ok) throw new Error("Room not found."); return response.json() as Promise<{ room: Values }>; }) : Promise.resolve(null)]).then(([options, room]) => { if (!active) return; setCategories(options.categories); setFloors(options.floors); if (room) setValues(room.room); }).catch((reason: unknown) => { if (active) setError(reason instanceof Error ? reason.message : "Unable to load room."); }).finally(() => { if (active) setLoading(false); }); return () => { active = false; }; }, [id, locale]);
  function change<Key extends keyof Values>(key: Key, value: Values[Key]) { setValues((current) => ({ ...current, [key]: value })); }
  async function save(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (saving) return; setSaving(true); setError(""); try { const response = await fetch(id ? `/api/housekeeping/rooms/${id}` : "/api/housekeeping/rooms", { method: id ? "PATCH" : "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ ...values, locale }) }); if (!response.ok) { const result = await response.json().catch(() => null) as { error?: string } | null; throw new Error(result?.error === "ROOM_NUMBER_EXISTS" ? "This room number already exists." : "Unable to save room."); } router.push("/housekeeping/settings/rooms"); router.refresh(); } catch (reason) { setError(reason instanceof Error ? reason.message : "Unable to save room."); setSaving(false); } }
  return <AppShell activeItem="housekeeping" pageTitle={t.housekeeping}><main className="p-4 sm:p-5 lg:p-7"><Link href="/housekeeping/settings/rooms" className="mb-4 inline-flex text-[12.5px] font-semibold text-[var(--qf-text-muted)]">← {t.back}</Link><section className="max-w-2xl rounded-[10px] border border-[var(--qf-border)] bg-white shadow-[var(--qf-shadow)]"><header className="border-b border-[var(--qf-border)] px-5 py-[14px] text-[14px] font-bold">{id ? t.edit : t.addRoom}</header>{loading ? <BrandLoader label={requestMessages[locale].loading} /> : <form className="space-y-4 p-5" onSubmit={save}><div className="grid gap-4 sm:grid-cols-2"><label className="block text-[12px] font-semibold text-[var(--qf-text-muted)]"><span className="mb-1.5 block">{t.roomNumber}</span><input className="qf-field" value={values.number} onChange={(event) => change("number", event.target.value)} required /></label><label className="block text-[12px] font-semibold text-[var(--qf-text-muted)]"><span className="mb-1.5 block">{t.roomName}</span><input className="qf-field" value={values.name} onChange={(event) => change("name", event.target.value)} /></label><label className="block text-[12px] font-semibold text-[var(--qf-text-muted)]"><span className="mb-1.5 block">{t.category}</span><select className="qf-field" value={values.categoryId} onChange={(event) => change("categoryId", event.target.value)}><option value="">—</option>{categories.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label className="block text-[12px] font-semibold text-[var(--qf-text-muted)]"><span className="mb-1.5 block">{t.floor}</span><select className="qf-field" value={values.floorId} onChange={(event) => change("floorId", event.target.value)}><option value="">—</option>{floors.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label></div><Checklist label={t.roomChecks} values={values.roomChecks} placeholder={t.newCheck} onChange={(roomChecks) => change("roomChecks", roomChecks)} /><Checklist label={t.arrivalChecks} values={values.arrivalChecks} placeholder={t.newArrivalCheck} onChange={(arrivalChecks) => change("arrivalChecks", arrivalChecks)} />{error ? <p role="alert" className="text-sm text-red-700">{error}</p> : null}<div className="flex gap-2 border-t border-[var(--qf-border)] pt-4"><button disabled={saving} className="min-h-[34px] rounded-[7px] bg-[var(--qf-accent)] px-[14px] text-[13px] font-semibold text-white disabled:opacity-60">{t.save}</button><Link href="/housekeeping/settings/rooms" className="inline-flex min-h-[34px] items-center rounded-[7px] border border-[var(--qf-border)] px-[14px] text-[13px] font-semibold">{t.cancel}</Link></div></form>}</section></main>{saving ? <BrandLoader label={requestMessages[locale].loading} overlay /> : null}</AppShell>;
}
