"use client";

import Link from "next/link";
import type { HousekeepingMessages } from "../../lib/i18n/housekeeping-messages";
import {categories,extraJobs,rooms} from "../../lib/housekeeping/preview-data";

const action="inline-flex min-h-[34px] items-center rounded-[7px] bg-[var(--qf-accent)] px-[14px] text-[12px] font-semibold text-white";

function AddAction({href,label}:{href:string;label:string}){return <div className="mb-[10px] flex justify-end"><Link href={href} className={action}>+ {label}</Link></div>}

export function FloorsSettings({t}:{t:HousekeepingMessages}){return <><AddAction href="/housekeeping/settings/floors/new" label={t.addFloor}/><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{[["1",10],["2",6]].map(([floor,count])=><article key={floor} className="flex min-h-[64px] items-center justify-between rounded-[8px] border border-[var(--qf-border)] bg-white px-4 py-[14px]"><div><h2 className="text-[13px] font-semibold">{t.floor} {floor}</h2><p className="mt-0.5 text-[11px] text-[var(--qf-text-light)]">{count} {t.roomCount}</p></div></article>)}<Link href="/housekeeping/settings/floors/new" className="flex min-h-[64px] items-center justify-center rounded-[8px] border border-dashed border-[var(--qf-border)] bg-white text-[12px] font-semibold text-[var(--qf-text-muted)]">+ {t.addFloor}</Link></div></>}

export function CategoriesSettings({t}:{t:HousekeepingMessages}){return <><AddAction href="/housekeeping/settings/categories/new" label={t.addCategory}/><section className="rounded-[10px] border border-[var(--qf-border)] bg-white px-5 shadow-[var(--qf-shadow)]">{categories.map((category,index)=><article key={category.name} className="flex min-h-[55px] items-center gap-3 border-b border-[var(--qf-border)] py-[10px] last:border-0"><span className="flex h-[34px] w-[34px] shrink-0 items-center justify-center rounded-[8px] bg-[var(--qf-accent-soft)] text-[15px]">🛏️</span><div className="min-w-0 flex-1"><h2 className="text-[13px] font-semibold">{category.name}</h2><p className="mt-0.5 text-[11px] text-[var(--qf-text-light)]">Express {category.express} {t.minutes} · Normal {category.normal} {t.minutes} · {t.departures} {category.departure} {t.minutes} · End {category.final} {t.minutes}</p></div><Link href={`/housekeeping/settings/categories/new?edit=${index}`} title={t.edit} aria-label={`${t.edit}: ${category.name}`} className="flex h-8 w-8 items-center justify-center rounded-[7px] border border-[var(--qf-border)] text-[13px]">✏️</Link></article>)}</section></>}

export function RoomsSettings({t}:{t:HousekeepingMessages}){return <><AddAction href="/housekeeping/settings/rooms/new" label={t.addRoom}/><section className="overflow-x-auto rounded-[10px] border border-[var(--qf-border)] bg-white shadow-[var(--qf-shadow)]"><table className="w-full min-w-[650px] border-collapse text-left text-[13px]"><thead><tr className="bg-[#f9f8f6] text-[11px] font-semibold uppercase tracking-[.5px] text-[var(--qf-text-light)]"><th className="px-3 py-2">{t.room}</th><th className="px-3 py-2">{t.category}</th><th className="px-3 py-2">{t.floor}</th><th className="px-3 py-2 text-right">{t.actions}</th></tr></thead><tbody>{rooms.map(room=><tr key={room.number} className="border-t border-[var(--qf-border)] hover:bg-[#fafaf8]"><td className="px-3 py-[9px] font-semibold">RN_{room.number} ({room.number})</td><td className="px-3 py-[9px]">{room.category}</td><td className="px-3 py-[9px]">{room.floor}</td><td className="px-3 py-[9px] text-right"><Link href={`/housekeeping/settings/rooms/new?edit=${room.number}`} title={t.edit} className="inline-flex h-8 w-8 items-center justify-center rounded-[7px] border border-[var(--qf-border)] text-[13px]">✏️</Link></td></tr>)}</tbody></table></section></>}

export function ExtraJobsSettings({t}:{t:HousekeepingMessages}){return <><AddAction href="/housekeeping/settings/extras/new" label={t.addExtra}/><section className="rounded-[10px] border border-[var(--qf-border)] bg-white px-5 shadow-[var(--qf-shadow)]">{extraJobs.map(([name,time],index)=><article key={name} className="flex min-h-[55px] items-center gap-3 border-b border-[var(--qf-border)] py-[10px] last:border-0"><span className="flex h-[34px] w-[34px] shrink-0 items-center justify-center rounded-[8px] bg-[var(--qf-accent-soft)] text-[15px]">🧹</span><div className="min-w-0 flex-1"><h2 className="text-[13px] font-semibold">{name}</h2><p className="mt-0.5 text-[11px] text-[var(--qf-text-light)]">{time} {t.minutes}</p></div><Link href={`/housekeeping/settings/extras/new?edit=${index}`} title={t.edit} aria-label={`${t.edit}: ${name}`} className="flex h-8 w-8 items-center justify-center rounded-[7px] border border-[var(--qf-border)] text-[13px]">✏️</Link></article>)}</section></>}
