"use client";

import { useEffect, useRef, useState, type FormEvent, type RefObject } from "react";
import { useRouter } from "next/navigation";
import { AppShell } from "../../../components/dashboard/app-shell";
import { Button } from "../../../components/ui/button";
import { Input } from "../../../components/ui/input";
import { BrandLoader } from "../../../components/ui/brand-loader";
import { useToast } from "../../../components/ui/toast-provider";
import { listProvinces } from "../../../lib/geo/locations";
import { accountSettingsMessages, type Locale } from "../../../lib/i18n/dictionaries";
import { HotelSettingsForm, type HotelSettingsValues } from "../../../components/settings/hotel-settings-form";
import { useI18n } from "../../../components/i18n/i18n-provider";
import { RichTextEditor, type RichTextEditorHandle } from "../../../components/recruiting/rich-text-editor";

type UserForm={firstName:string;lastName:string;email:string;phoneNumber:string;language:string;role:string};
type HotelForm=HotelSettingsValues&{dataProtectionEn:string;dataProtectionDe:string;dataProtectionIt:string;privacyPolicyEn:string;privacyPolicyDe:string;privacyPolicyIt:string};
const emptyUser:UserForm={firstName:"",lastName:"",email:"",phoneNumber:"",language:"EN",role:""};
const dataKeys={en:"dataProtectionEn",de:"dataProtectionDe",it:"dataProtectionIt"} as const;
const privacyKeys={en:"privacyPolicyEn",de:"privacyPolicyDe",it:"privacyPolicyIt"} as const;

function mapUser(u:Record<string,string|null>):UserForm{return{firstName:u.first_name??"",lastName:u.last_name??"",email:u.email??"",phoneNumber:u.phone_number??"",language:u.language??"EN",role:u.role??""}}
function text(value:unknown){return typeof value==="string"?value:""}
function mapHotel(h:Record<string,unknown>):HotelForm{return{hotelNameEn:text(h.hotel_name_en),hotelNameDe:text(h.hotel_name_de),hotelNameIt:text(h.hotel_name_it),email:text(h.email),logoUrl:text(h.logo_url),companyName:text(h.company_name),streetAddress:text(h.street_address),postalCode:text(h.postal_code),city:text(h.city),country:text(h.country),province:text(h.province),contactPerson:text(h.contact_person),phoneNumber:text(h.phone_number),vatId:text(h.vat_id),tripadvisorId:text(h.tripadvisor_id),asaXmlName:text(h.asa_xml_name),timeZone:text(h.time_zone),hotelLanguage:text(h.hotel_language)||"EN",pecAddress:text(h.pec_address),invoiceEmail:text(h.invoice_email),sdiCode:text(h.sdi_code),legalForm:text(h.legal_form),roomCount:h.room_count==null?"":String(h.room_count),starRating:h.star_rating==null?"":String(h.star_rating),seasonal:h.seasonal===true,openingPeriod:text(h.opening_period),closurePeriod:text(h.closure_period),checkInTime:text(h.check_in_time),checkOutTime:text(h.check_out_time),pmsName:text(h.pms_name),dataProtectionEn:text(h.data_protection_en),dataProtectionDe:text(h.data_protection_de),dataProtectionIt:text(h.data_protection_it),privacyPolicyEn:text(h.privacy_policy_en),privacyPolicyDe:text(h.privacy_policy_de),privacyPolicyIt:text(h.privacy_policy_it)}}

export default function AccountSettingsPage(){
 const{locale,setLocale}=useI18n();const t=accountSettingsMessages[locale];const toast=useToast();const router=useRouter();const[user,setUser]=useState(emptyUser);const[hotel,setHotel]=useState<HotelForm|null>(null);const[loading,setLoading]=useState(true);const[busy,setBusy]=useState(false);const readPolicies=useRef<(()=>Partial<HotelForm>)|null>(null);
 useEffect(()=>{fetch("/api/settings/account").then(async r=>{if(r.status===401)return router.replace("/login");if(!r.ok)throw new Error();const d=await r.json();setUser(mapUser(d.user));setHotel(d.hotel?mapHotel(d.hotel):null)}).catch(()=>toast({message:t.error,tone:"error"})).finally(()=>setLoading(false))},[router,t.error,toast]);
 async function save(section:"user"|"hotel",event:FormEvent){event.preventDefault();setBusy(true);const named=hotel?{...hotel,hotelNameEn:hotel.hotelNameEn.trim()||hotel[locale==="de"?"hotelNameDe":locale==="it"?"hotelNameIt":"hotelNameEn"].trim(),hotelNameDe:hotel.hotelNameDe.trim()||hotel[locale==="de"?"hotelNameDe":locale==="it"?"hotelNameIt":"hotelNameEn"].trim(),hotelNameIt:hotel.hotelNameIt.trim()||hotel[locale==="de"?"hotelNameDe":locale==="it"?"hotelNameIt":"hotelNameEn"].trim()}:hotel;const payload=section==="user"?user:named?{...named,...readPolicies.current?.(),policyLocale:locale}:named;try{const r=await fetch("/api/settings/account",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({section,...payload})});const d=await r.json();if(!r.ok){toast({message:d.error==="INVALID_ASA_XML_NAME"?t.invalidAsaXmlName:d.error==="EMAIL_EXISTS"?t.exists:d.error==="INVALID_FIELDS"?t.required:t.error,tone:"error"});return}if(section==="hotel"&&d.policies)setHotel(current=>current?{...current,...d.policies}:current);toast({message:t.saved,tone:"success"});if(section==="user")setLocale(user.language.toLowerCase() as "en"|"de"|"it")}catch{toast({message:t.error,tone:"error"})}finally{setBusy(false)}}
 const userRequired=!user.firstName||!user.lastName||!user.email;const hotelName=hotel?.[locale==="de"?"hotelNameDe":locale==="it"?"hotelNameIt":"hotelNameEn"]??"";const hotelRequired=hotel&&(!hotelName||!hotel.email||!hotel.companyName||!hotel.streetAddress||!hotel.postalCode||!hotel.city||!hotel.country||(listProvinces(hotel.country).length>0&&!hotel.province)||!hotel.contactPerson);
 return <AppShell activeItem="settings"><main className="p-4 sm:p-5 lg:p-7"><button onClick={()=>router.push("/settings")} className="mb-3.5 cursor-pointer text-[12.5px] font-semibold text-[var(--qf-text-muted)]">← {t.back}</button><h1 className="mb-5 text-xl font-bold">{t.title}</h1>{loading?<BrandLoader/>:<div className="space-y-5"><Section title={t.profile} help={t.profileHelp}><form onSubmit={e=>void save("user",e)} noValidate><div className="grid gap-4 p-5 sm:grid-cols-2"><Input label={t.first} value={user.firstName} error={!user.firstName?t.required:undefined} onChange={e=>setUser({...user,firstName:e.target.value})}/><Input label={t.last} value={user.lastName} error={!user.lastName?t.required:undefined} onChange={e=>setUser({...user,lastName:e.target.value})}/><Input type="email" label={t.email} value={user.email} error={!user.email?t.required:undefined} onChange={e=>setUser({...user,email:e.target.value})}/><Input label={t.phone} value={user.phoneNumber} onChange={e=>setUser({...user,phoneNumber:e.target.value})}/><label className="space-y-1.5 text-[13px] font-semibold">{t.language}<select value={user.language} onChange={e=>setUser({...user,language:e.target.value})} className="block h-11 w-full cursor-pointer rounded-lg border border-[var(--qf-border)] bg-white px-3.5 text-sm font-normal"><option value="EN">English</option><option value="DE">Deutsch</option><option value="IT">Italiano</option></select></label></div><Footer><Button type="submit" disabled={Boolean(userRequired)||busy}>{t.save}</Button></Footer></form></Section>{hotel?<Section title={t.hotel} help={t.hotelHelp}><form onSubmit={e=>void save("hotel",e)} noValidate><HotelSettingsForm hotel={hotel} setHotel={setHotel} locale={locale} t={t} /><PolicyFields hotel={hotel} setHotel={setHotel} locale={locale} onRead={read=>{readPolicies.current=read}} labels={{dataProtection:t.dataProtection,privacyPolicy:t.privacyPolicy,policyHelp:t.policyHelp}}/><Footer><Button type="submit" disabled={Boolean(hotelRequired)||busy}>{t.save}</Button></Footer></form></Section>:null}</div>}{busy?<BrandLoader overlay/>:null}</main></AppShell>
}
function PolicyFields({hotel,setHotel,locale,onRead,labels}:{hotel:HotelForm;setHotel:(hotel:HotelForm|((current:HotelForm|null)=>HotelForm|null))=>void;locale:Locale;onRead:(read:()=>Partial<HotelForm>)=>void;labels:{dataProtection:string;privacyPolicy:string;policyHelp:string}}){
 const dataRef=useRef<RichTextEditorHandle>(null);
 const privacyRef=useRef<RichTextEditorHandle>(null);
 const dataKey=dataKeys[locale];
 const privacyKey=privacyKeys[locale];
 function currentPolicies(){return{[dataKey]:dataRef.current?.getHtml()??hotel[dataKey],[privacyKey]:privacyRef.current?.getHtml()??hotel[privacyKey]}}
 useEffect(()=>{onRead(currentPolicies)},[dataKey,hotel,onRead,privacyKey]);
 return <div className="space-y-4 border-t border-[var(--qf-border)] px-5 py-5"><p className="max-w-xl text-xs text-[var(--qf-text-muted)]">{labels.policyHelp}</p><PolicyEditor editorRef={dataRef} label={labels.dataProtection} value={hotel[dataKey]} locale={locale} onChange={html=>setHotel(current=>current?{...current,[dataKey]:html}:current)}/><PolicyEditor editorRef={privacyRef} label={labels.privacyPolicy} value={hotel[privacyKey]} locale={locale} onChange={html=>setHotel(current=>current?{...current,[privacyKey]:html}:current)}/></div>;
}
function PolicyEditor({editorRef,label,value,locale,onChange}:{editorRef:RefObject<RichTextEditorHandle|null>;label:string;value:string;locale:Locale;onChange:(html:string)=>void}){return <div className="space-y-1.5"><p className="text-[13px] font-semibold">{label}</p><div className="settings-policy-editor"><RichTextEditor ref={editorRef} key={locale} value={value} onChange={onChange} placeholder={label} locale={locale} height={220}/></div></div>}
function Section({title,help,children}:{title:string;help:string;children:React.ReactNode}){return <section className="overflow-visible rounded-[var(--qf-radius)] border border-[var(--qf-border)] bg-white shadow-[var(--qf-shadow)]"><header className="border-b border-[var(--qf-border)] px-5 py-4"><h2 className="text-sm font-bold">{title}</h2><p className="mt-1 text-xs text-[var(--qf-text-muted)]">{help}</p></header>{children}</section>}
function Footer({children}:{children:React.ReactNode}){return <footer className="flex justify-end border-t border-[var(--qf-border)] bg-[#fafaf8] p-4">{children}</footer>}
