"use client";

import { useCallback, useEffect, useState, type FormEvent } from "react";
import { useParams, useRouter, useSearchParams } from "next/navigation";
import { AppShell } from "../../../../components/dashboard/app-shell";
import { useI18n } from "../../../../components/i18n/i18n-provider";
import { FileDropZone } from "../../../../components/settings/file-drop-zone";
import { BrandLoader } from "../../../../components/ui/brand-loader";
import { getKnowledgeMessages } from "../../../../lib/i18n/knowledge-messages";

type Department = { id: string; nameEn: string; nameDe: string; nameIt: string; mcpDepartmentId: string };
type KnowledgeFile = { id: string; filename?: string; name?: string; status?: string; attributes?: { title?: string; tags?: string | string[]; description?: string } };

export default function KnowledgeDetailPage() {
  const params = useParams<{ scope: string }>(); const query = useSearchParams(); const router = useRouter(); const { locale } = useI18n(); const t = getKnowledgeMessages(locale); const storeId = params.scope; const storeName = query.get("name") || t.knowledgeTitle; const mcpDepartmentId = query.get("deptId") || "";
  const copy = locale === "de" ? { add: "KI-Wissen hinzufügen", title: "Titel", department: "Abteilung", tags: "Tags (durch Kommas getrennt)", instructions: "Anweisungen", files: "Dateien (max. 20)", save: "Speichern", cancel: "Abbrechen", loading: "KI-Wissen wird geladen…", empty: "Noch kein KI-Wissen vorhanden.", required: "Dateien, Titel, Abteilung und Anweisungen sind erforderlich.", limit: "Maximal 20 Dateien und 510 Zeichen ohne Leerzeichen sind erlaubt.", uploaded: "Dateien wurden hochgeladen und werden verarbeitet.", deleted: "Datei gelöscht.", failed: "Die Anfrage ist fehlgeschlagen.", deleteConfirm: "Diese Datei wirklich löschen?" } : locale === "it" ? { add: "Aggiungi conoscenza IA", title: "Titolo", department: "Reparto", tags: "Tag (separati da virgole)", instructions: "Istruzioni", files: "File (massimo 20)", save: "Salva", cancel: "Annulla", loading: "Caricamento conoscenza IA…", empty: "Nessuna conoscenza IA presente.", required: "File, titolo, reparto e istruzioni sono obbligatori.", limit: "Sono consentiti massimo 20 file e 510 caratteri senza spazi.", uploaded: "I file sono stati caricati e sono in elaborazione.", deleted: "File eliminato.", failed: "Richiesta non riuscita.", deleteConfirm: "Eliminare questo file?" } : { add: "Add AI knowledge", title: "Title", department: "Department", tags: "Tags (comma separated)", instructions: "Instructions", files: "Files (max. 20)", save: "Save", cancel: "Cancel", loading: "Loading AI knowledge…", empty: "No AI knowledge added yet.", required: "Files, title, department, and instructions are required.", limit: "A maximum of 20 files and 510 non-space instruction characters is allowed.", uploaded: "Files uploaded and are being processed.", deleted: "File deleted.", failed: "The request failed.", deleteConfirm: "Delete this file?" };
  const endpoint = `/api/settings/knowledge/vector-stores/${encodeURIComponent(storeId)}/files`;
  const [files, setFiles] = useState<KnowledgeFile[]>([]); const [departments, setDepartments] = useState<Department[]>([]); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [modal, setModal] = useState(false); const [selectedFiles, setSelectedFiles] = useState<File[]>([]); const [title, setTitle] = useState(""); const [departmentId, setDepartmentId] = useState(""); const [tags, setTags] = useState(""); const [description, setDescription] = useState(""); const [notice, setNotice] = useState("");
  const load = useCallback(async () => { const response = await fetch(endpoint, { cache: "no-store" }); const data = await response.json(); if (!response.ok) throw new Error(data.message || copy.failed); setFiles(Array.isArray(data.files) ? data.files : []); setDepartments(Array.isArray(data.departments) ? data.departments : []); return data.departments as Department[]; }, [copy.failed, endpoint]);
  useEffect(() => { let active = true; fetch(endpoint, { cache: "no-store" }).then(async response => { const data = await response.json(); if (!response.ok) throw new Error(data.message || copy.failed); return data; }).then(data => { if (active) { const nextDepartments = Array.isArray(data.departments) ? data.departments : []; setFiles(Array.isArray(data.files) ? data.files : []); setDepartments(nextDepartments); setDepartmentId(nextDepartments.find((department: Department) => department.mcpDepartmentId === mcpDepartmentId)?.id || ""); } }).catch((error: unknown) => { if (active) setNotice(error instanceof Error ? error.message : copy.failed); }).finally(() => { if (active) setLoading(false); }); return () => { active = false; }; }, [copy.failed, endpoint, mcpDepartmentId]);
  const departmentName = (department: Department) => locale === "de" ? department.nameDe : locale === "it" ? department.nameIt : department.nameEn;
  function closeModal() { if (saving) return; setModal(false); setSelectedFiles([]); setTitle(""); setTags(""); setDescription(""); }
  async function upload(event: FormEvent) { event.preventDefault(); if (!selectedFiles.length || !title.trim() || !departmentId || !description.trim()) return setNotice(copy.required); if (selectedFiles.length > 20 || description.replace(/\s+/g, "").length > 510) return setNotice(copy.limit); setSaving(true); setNotice(""); const form = new FormData(); form.set("title", title.trim()); form.set("departmentId", departmentId); form.set("description", description.trim()); form.set("tags", tags); selectedFiles.forEach(file => form.append("files", file)); try { const response = await fetch(endpoint, { method: "POST", body: form }); const data = await response.json(); if (!response.ok) throw new Error(data.message || copy.failed); await load(); closeModal(); setModal(false); setSelectedFiles([]); setTitle(""); setTags(""); setDescription(""); setNotice(copy.uploaded); } catch (error) { setNotice(error instanceof Error ? error.message : copy.failed); } finally { setSaving(false); } }
  async function remove(file: KnowledgeFile) { if (saving || !window.confirm(copy.deleteConfirm)) return; setSaving(true); setNotice(""); try { const response = await fetch(`${endpoint}?fileId=${encodeURIComponent(file.id)}`, { method: "DELETE" }); const data = await response.json(); if (!response.ok) throw new Error(data.message || copy.failed); setFiles(items => items.filter(item => item.id !== file.id)); setNotice(copy.deleted); } catch (error) { setNotice(error instanceof Error ? error.message : copy.failed); } finally { setSaving(false); } }
  return <AppShell activeItem="settings" pageTitle={t.knowledgeTitle}><main className="p-4 sm:p-5 lg:px-7 lg:py-6"><button type="button" onClick={() => router.push("/settings/knowledge")} className="mb-5 cursor-pointer text-[12.5px] font-semibold text-[var(--qf-text-muted)] hover:text-[var(--qf-accent)]">← {t.knowledgeTitle}</button>
    <section className="overflow-hidden rounded-[var(--qf-radius)] border border-[var(--qf-border)] bg-white shadow-[var(--qf-shadow)]"><header className="flex flex-col gap-3 border-b border-[var(--qf-border)] px-4 py-4 sm:flex-row sm:items-center sm:justify-between sm:px-5"><div><h1 className="text-[14px] font-bold">📚 {storeName}</h1><p className="mt-1 text-[11.5px] text-[var(--qf-text-muted)]">{t.department} · {files.length} {files.length === 1 ? t.document : t.documents} · {t.sharedWithManuals}</p></div><code className="w-fit rounded-md bg-[var(--qf-background)] px-2.5 py-1.5 text-[10px] text-[var(--qf-text-muted)]">{storeId}</code></header>
      <div className="p-4 sm:p-5"><FileDropZone label={t.uploadDocument} messages={t} onFiles={selected => { setSelectedFiles(selected); setModal(true); }} fileTypes=".pdf,.doc,.docx,.txt,.jpg,.jpeg,.png,application/pdf,text/plain,image/jpeg,image/png" />{notice ? <p role="status" className="mt-3 rounded-md bg-[var(--qf-accent-soft)] px-3 py-2 text-[11.5px]">{notice}</p> : null}<div className="mt-4">{!loading && files.length ? files.map(file => <div key={file.id} className="flex items-center gap-3 border-b border-[var(--qf-border)] py-3 last:border-0"><span className="flex h-9 w-9 shrink-0 items-center justify-center rounded-lg bg-[var(--qf-background)]">📄</span><span className="min-w-0 flex-1"><span className="block truncate text-[12.5px] font-semibold">{file.attributes?.title || file.filename || file.name || file.id}</span><span className="mt-0.5 block truncate text-[10.5px] text-[var(--qf-text-light)]">{file.attributes?.tags ? (Array.isArray(file.attributes.tags) ? file.attributes.tags.join(", ") : file.attributes.tags) : file.status || t.current}</span></span><button type="button" onClick={() => void remove(file)} aria-label={`${t.remove}: ${file.attributes?.title || file.id}`} title={t.remove} className="flex h-8 w-8 shrink-0 cursor-pointer items-center justify-center rounded-md text-sm text-[var(--qf-text-light)] transition hover:bg-red-50 hover:text-red-600">🗑️</button></div>) : !loading ? <p className="py-8 text-center text-xs text-[var(--qf-text-light)]">{copy.empty}</p> : null}</div></div></section>
    <p className="mt-3 text-[10.5px] text-[var(--qf-text-light)]">ⓘ {t.previewNote}</p>
    {modal ? <div className="fixed inset-0 z-[100] flex items-center justify-center bg-black/45 p-4" onMouseDown={event => event.target === event.currentTarget && closeModal()}><div role="dialog" aria-modal="true" className="max-h-[90vh] w-full max-w-[520px] overflow-y-auto rounded-xl bg-white shadow-2xl"><header className="flex items-center justify-between border-b border-[var(--qf-border)] px-5 py-4"><h2 className="text-[15px] font-bold">{copy.add}</h2><button type="button" onClick={closeModal} className="h-7 w-7 cursor-pointer rounded-md hover:bg-[var(--qf-background)]">×</button></header><form onSubmit={upload}><div className="space-y-4 px-5 py-5"><p className="text-[11px] text-[var(--qf-text-muted)]">{selectedFiles.map(file => file.name).join(", ")}</p><label className="block text-xs font-semibold">{copy.title}<input value={title} onChange={event => setTitle(event.target.value)} className="mt-1.5 h-10 w-full rounded-lg border border-[var(--qf-border)] px-3 text-xs" /></label><label className="block text-xs font-semibold">{copy.department}<select value={departmentId} onChange={event => setDepartmentId(event.target.value)} className="mt-1.5 h-10 w-full rounded-lg border border-[var(--qf-border)] bg-white px-3 text-xs"><option value="">-- {copy.department} --</option>{departments.map(department => <option key={department.id} value={department.id}>{departmentName(department)}</option>)}</select></label><label className="block text-xs font-semibold">{copy.tags}<input value={tags} onChange={event => setTags(event.target.value)} className="mt-1.5 h-10 w-full rounded-lg border border-[var(--qf-border)] px-3 text-xs" /></label><label className="block text-xs font-semibold">{copy.instructions}<textarea value={description} onChange={event => setDescription(event.target.value)} rows={4} className="mt-1.5 w-full rounded-lg border border-[var(--qf-border)] px-3 py-2 text-xs" /></label></div><footer className="flex justify-end gap-2.5 border-t border-[var(--qf-border)] px-5 py-4"><button type="button" onClick={closeModal} className="h-9 rounded-lg border border-[var(--qf-border)] px-4 text-xs font-semibold">{copy.cancel}</button><button type="submit" disabled={saving} className="h-9 rounded-lg bg-[var(--qf-accent)] px-4 text-xs font-semibold text-white disabled:opacity-60">{copy.save}</button></footer></form></div></div> : null}
    {loading || saving ? <BrandLoader label={copy.loading} overlay /> : null}
  </main></AppShell>;
}
