"use client";
import {useEffect,useMemo,useState,type ReactNode} from "react";
import {usePathname} from "next/navigation";
import {AppShell} from "../../components/dashboard/app-shell";
import {useI18n} from "../../components/i18n/i18n-provider";
type View="overview"|"list"|"create"|"detail";type Status="offen"|"erledigt";type Handover={id:number;title:string;creator:string;departments:string;visibility:string;status:Status;date:string;description:string};
const data:Handover[]=[{id:1,title:"Tägliche Übergabe Reception",creator:"Klaus",departments:"Rezeption",visibility:"Bestimmte Abteilungen",status:"offen",date:"17.08.2026",description:"Zimmer 48 – Extra-Handtücher bitte bis 16:00 liefern.\n\nTischreservierung um 19:30 Uhr für 7 Personen bestätigt. Tisch 4 + 5 zusammenstellen.\n\nMilchbestand prüfen und Zimmerschlüssel 46 an den Gast übergeben."},{id:2,title:"To Do Winter",creator:"Marion (Reception)",departments:"Rezeption",visibility:"Bestimmte Abteilungen",status:"offen",date:"22.01.2026",description:"Winteraufgaben und offene Punkte für die nächste Schicht."},{id:3,title:"Marketing 2026",creator:"Klaus",departments:"–",visibility:"Nur ich",status:"offen",date:"02.03.2026",description:"Marketingplanung und nächste Schritte für 2026."},{id:4,title:"SEO nach Fragen suchen",creator:"Klaus",departments:"–",visibility:"Alle",status:"erledigt",date:"17.11.2025",description:"SEO-Fragen wurden geprüft und dokumentiert."}];
const card="rounded-[var(--qf-radius)] border border-[var(--qf-border)] bg-white shadow-[var(--qf-shadow)]",btn="inline-flex min-h-10 cursor-pointer items-center justify-center rounded-[7px] border px-4 text-[12.5px] font-semibold";
function HandoversUI({initialView="overview"}:{initialView?:View}){const[view,setView]=useState<View>(initialView),[filter,setFilter]=useState<"alle"|Status>("alle"),[search,setSearch]=useState(""),[selected,setSelected]=useState(data[0]),[visibility,setVisibility]=useState("alle");const filtered=useMemo(()=>data.filter(x=>(filter==="alle"||x.status===filter)&&`${x.title} ${x.creator} ${x.departments}`.toLowerCase().includes(search.toLowerCase())),[filter,search]);const detail=(x:Handover)=>{setSelected(x);setView("detail")};return <AppShell activeItem="handovers"><main className="p-4 sm:p-5 lg:p-7">
{view!=="overview"?<button onClick={()=>setView(view==="list"?"overview":"list")} className="mb-4 cursor-pointer text-[12.5px] font-semibold text-[var(--qf-text-muted)]">← Übergaben</button>:null}
{view==="overview"?<div className="grid gap-5 xl:grid-cols-[minmax(0,1.35fr)_minmax(320px,.65fr)]"><section><Title>Aktuelle Übergaben</Title><article className={`${card} mb-3 p-4`}><div className="mb-3 flex flex-wrap items-center gap-2"><Badge>Frühschicht → Mittelschicht</Badge><span className="text-xs text-[var(--qf-text-muted)] sm:ml-auto">Maria R. → Jana M. · 15:00</span></div><Block title="⚠️ Dringendes">Zimmer 48 – Gast Fam. Mayer hat um Extra-Handtücher gebeten, bitte bis 16:00 liefern. Tischreservierung 19:30 Uhr für 7 Personen bestätigt – Tisch 4+5 zusammenstellen.</Block><Block title="🏷 Besondere Gäste"><Guest room="Zi. 52">Fam. Hofer – 10. Hochzeitstag, Willkommenspaket vorbereitet ✅</Guest><Guest room="Zi. 44">Hr. Brunner – VIP, früher Check-in bestätigt</Guest></Block><Block title="📦 Lager & Sonstiges">Marmelade & Honig nachgeordert ✅ · Milch bitte noch prüfen · Schlüssel Zi. 46 liegt an der Rezeption</Block></article><Pending title="Spätschicht → Nachtschicht" meta="Jana M. → Nachtdienst · 23:00" text="Noch nicht ausgefüllt · Fällig um 22:30"/><Pending title="Restaurant-Übergabe" meta="Luca B. · 22:00" text="Noch nicht ausgefüllt"/></section><aside className="space-y-4"><section className={card}><Head>✨ KI-Zusammenfassung</Head><div className="p-4 text-[13px] leading-6"><p><b>Heute im Fokus:</b> 10 Ankünfte, darunter 2 VIP-Gäste. Express-Zimmer 45 & 51 sind Toppriorität.</p><p className="mt-3"><b>Offene Punkte:</b> Handtücher Zi. 48, Milch nachbestellen, Schlüssel Zi. 46 übergeben.</p><p className="mt-3"><b>Personalhinweis:</b> Frühstücksvertretung noch ungeklärt.</p><button onClick={()=>setView("create")} className={`${btn} mt-4 w-full border-[#7c3aed] bg-[#7c3aed] text-white`}>✨ Neue Übergabe mit KI ausfüllen</button></div></section><section className={card}><Head action={<button onClick={()=>setView("list")} className="cursor-pointer text-[var(--qf-accent)]">Alle →</button>}>📅 Übergaben-Verlauf</Head><div className="divide-y">{data.map(x=><button key={x.id} onClick={()=>detail(x)} className="flex w-full cursor-pointer items-center gap-3 p-3 text-left"><span className="flex h-8 w-8 items-center justify-center rounded-full bg-green-100">{x.status==="erledigt"?"✓":"📋"}</span><span className="min-w-0 flex-1"><b className="block truncate text-xs">{x.title}</b><small className="text-[10.5px] text-[var(--qf-text-muted)]">{x.date} · {x.creator}</small></span><Pill status={x.status}/></button>)}</div></section><button onClick={()=>setView("list")} className={`${btn} w-full border-[var(--qf-border)] bg-white`}>📋 Alle Übergaben verwalten</button></aside></div>:null}
{view==="list"?<section><div className="mb-4 flex flex-wrap items-center gap-2"><div className="flex rounded-lg border bg-white p-1">{(["alle","offen","erledigt"] as const).map(x=><button key={x} onClick={()=>setFilter(x)} className={`cursor-pointer rounded-md px-3 py-2 text-xs font-semibold capitalize ${filter===x?"bg-[var(--qf-accent-soft)] text-[var(--qf-accent)]":"text-[var(--qf-text-muted)]"}`}>{x}</button>)}</div><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="🔍 Suchen..." className="h-10 min-w-0 flex-1 rounded-lg border px-3 text-sm sm:max-w-60"/><button onClick={()=>setView("create")} className={`${btn} ml-auto border-[var(--qf-accent)] bg-[var(--qf-accent)] text-white`}><span className="sm:hidden">＋</span><span className="hidden sm:inline">+ Übergabe erstellen</span></button></div><div className="grid gap-3 md:hidden">{filtered.map(x=><button key={x.id} onClick={()=>detail(x)} className={`${card} p-4 text-left`}><div className="flex gap-3"><span className="text-xl">🤝</span><span className="min-w-0 flex-1"><b className="block text-[13px]">{x.title}</b><small className="block text-[11px] text-[var(--qf-text-muted)]">{x.creator} · {x.date}</small><small className="text-[11px] text-[var(--qf-text-muted)]">{x.departments}</small></span><Pill status={x.status}/></div></button>)}</div><div className={`${card} hidden overflow-x-auto md:block`}><table className="w-full min-w-[800px] text-xs"><thead><tr className="bg-[#f9f8f6] text-left text-[10.5px] text-[var(--qf-text-muted)]">{["Titel","Ersteller","Abteilungen","Sichtbarkeit","Status","Datum","Aktionen"].map(x=><th key={x} className="border-b px-4 py-3">{x}</th>)}</tr></thead><tbody>{filtered.map(x=><tr key={x.id} onClick={()=>detail(x)} className="cursor-pointer hover:bg-[#fafaf8]"><td className="border-b px-4 py-3 font-semibold">{x.title}</td><td className="border-b px-4 py-3">{x.creator}</td><td className="border-b px-4 py-3">{x.departments}</td><td className="border-b px-4 py-3">{x.visibility}</td><td className="border-b px-4 py-3"><Pill status={x.status}/></td><td className="border-b px-4 py-3">{x.date}</td><td className="border-b px-4 py-3">✏️</td></tr>)}</tbody></table></div></section>:null}
{view==="create"?<section className="grid gap-4 lg:grid-cols-[1.4fr_.6fr]"><div className={card}><Head>Inhalt</Head><div className="space-y-4 p-4"><Field label="Vorlage"><select className="qf-field"><option>Vorlage wählen...</option><option>Tägliche Reception-Übergabe</option><option>Wochenend-Übergabe Service</option></select></Field><Field label="Titel"><input className="qf-field" placeholder="Titel der Übergabe"/></Field><Field label="Beschreibung"><textarea className="qf-field min-h-56 resize-y" placeholder="Inhalt der Übergabe..."/></Field><p className="text-[11px] text-[var(--qf-text-muted)]">🌐 Schreib einfach in deiner Sprache – andere Mitarbeiter sehen automatisch ihre eigene Version.</p></div></div><div className="space-y-4"><div className={card}><Head>Sichtbarkeit</Head><div className="space-y-3 p-4">{[["alle","Alle (hotelweit)"],["dept","Bestimmte Abteilungen"],["privat","Nur ich"]].map(([id,label])=><label key={id} className="flex cursor-pointer gap-2 text-[13px]"><input type="radio" checked={visibility===id} onChange={()=>setVisibility(id)}/>{label}</label>)}</div></div><div className={card}><Head>Tags</Head><div className="p-4"><input className="qf-field" placeholder="Tag hinzufügen (Enter)"/></div></div><div className={`${card} space-y-2 p-4`}>{["Speichern","Als Entwurf speichern","💾 Als Vorlage speichern"].map((x,i)=><button key={x} className={`${btn} w-full ${i===0?"border-[var(--qf-accent)] bg-[var(--qf-accent)] text-white":"border-[var(--qf-border)] bg-white"}`}>{x}</button>)}</div></div></section>:null}
{view==="detail"?<article className={card}><Head action={<Pill status={selected.status}/>}><span>{selected.title}<small className="mt-1 block font-normal text-[var(--qf-text-muted)]">{selected.creator} · {selected.date}</small></span></Head><div className="p-4 text-[13.5px] leading-7 whitespace-pre-line">{selected.description}<div className="mt-5 flex gap-2"><Badge>{selected.departments}</Badge><Badge>{selected.visibility}</Badge></div></div><footer className="flex flex-wrap gap-2 border-t p-4"><button className={`${btn} border-[var(--qf-accent)] bg-[var(--qf-accent)] text-white`}>✓ Als erledigt markieren</button><button onClick={()=>setView("create")} className={`${btn} border-[var(--qf-border)] bg-white`}>✏️ Bearbeiten</button><label className="ml-auto flex items-center gap-2 text-xs"><input type="checkbox"/> 📌 Anpinnen</label></footer></article>:null}
</main></AppShell>}
export default function Page(){const pathname=usePathname();const{locale}=useI18n();useHandoverTranslation(locale);const initialView:View=pathname.endsWith("/list")?"list":pathname.endsWith("/create")?"create":pathname.endsWith("/detail")?"detail":"overview";return <HandoversUI initialView={initialView}/>}

type UiLocale="en"|"de"|"it";
const translations:Record<string,Record<UiLocale,string>>={
"Aktuelle Übergaben":{de:"Aktuelle Übergaben",en:"Current handovers",it:"Consegne attuali"},
"Frühschicht → Mittelschicht":{de:"Frühschicht → Mittelschicht",en:"Early shift → Mid shift",it:"Turno mattutino → Turno centrale"},
"⚠️ Dringendes":{de:"⚠️ Dringendes",en:"⚠️ Urgent",it:"⚠️ Urgente"},
"Zimmer 48 – Gast Fam. Mayer hat um Extra-Handtücher gebeten, bitte bis 16:00 liefern. Tischreservierung 19:30 Uhr für 7 Personen bestätigt – Tisch 4+5 zusammenstellen.":{de:"Zimmer 48 – Gast Fam. Mayer hat um Extra-Handtücher gebeten, bitte bis 16:00 liefern. Tischreservierung 19:30 Uhr für 7 Personen bestätigt – Tisch 4+5 zusammenstellen.",en:"Room 48 – The Mayer family requested extra towels; please deliver them by 4:00 PM. The 7-person dinner reservation for 7:30 PM is confirmed – combine tables 4 and 5.",it:"Camera 48 – La famiglia Mayer ha richiesto asciugamani extra; consegnarli entro le 16:00. La prenotazione per 7 persone alle 19:30 è confermata – unire i tavoli 4 e 5."},
"🏷 Besondere Gäste":{de:"🏷 Besondere Gäste",en:"🏷 Special guests",it:"🏷 Ospiti speciali"},
"Fam. Hofer – 10. Hochzeitstag, Willkommenspaket vorbereitet ✅":{de:"Fam. Hofer – 10. Hochzeitstag, Willkommenspaket vorbereitet ✅",en:"Hofer family – 10th wedding anniversary, welcome package prepared ✅",it:"Famiglia Hofer – 10° anniversario di matrimonio, pacchetto di benvenuto pronto ✅"},
"Hr. Brunner – VIP, früher Check-in bestätigt":{de:"Hr. Brunner – VIP, früher Check-in bestätigt",en:"Mr Brunner – VIP, early check-in confirmed",it:"Sig. Brunner – VIP, check-in anticipato confermato"},
"📦 Lager & Sonstiges":{de:"📦 Lager & Sonstiges",en:"📦 Stock & other items",it:"📦 Magazzino e altro"},
"Marmelade & Honig nachgeordert ✅ · Milch bitte noch prüfen · Schlüssel Zi. 46 liegt an der Rezeption":{de:"Marmelade & Honig nachgeordert ✅ · Milch bitte noch prüfen · Schlüssel Zi. 46 liegt an der Rezeption",en:"Jam and honey reordered ✅ · Please check the milk stock · The key for room 46 is at reception",it:"Marmellata e miele riordinati ✅ · Controllare la scorta di latte · La chiave della camera 46 è alla reception"},
"Spätschicht → Nachtschicht":{de:"Spätschicht → Nachtschicht",en:"Late shift → Night shift",it:"Turno serale → Turno notturno"},
"Noch nicht ausgefüllt · Fällig um 22:30":{de:"Noch nicht ausgefüllt · Fällig um 22:30",en:"Not completed yet · Due at 10:30 PM",it:"Non ancora compilata · Scadenza alle 22:30"},
"Restaurant-Übergabe":{de:"Restaurant-Übergabe",en:"Restaurant handover",it:"Consegna ristorante"},
"Noch nicht ausgefüllt":{de:"Noch nicht ausgefüllt",en:"Not completed yet",it:"Non ancora compilata"},
"✨ KI-Zusammenfassung":{de:"✨ KI-Zusammenfassung",en:"✨ AI summary",it:"✨ Riepilogo IA"},
"Heute im Fokus:":{de:"Heute im Fokus:",en:"Today’s focus:",it:"Priorità di oggi:"},
"10 Ankünfte, darunter 2 VIP-Gäste. Express-Zimmer 45 & 51 sind Toppriorität.":{de:"10 Ankünfte, darunter 2 VIP-Gäste. Express-Zimmer 45 & 51 sind Toppriorität.",en:"10 arrivals, including 2 VIP guests. Express rooms 45 and 51 are the top priority.",it:"10 arrivi, inclusi 2 ospiti VIP. Le camere express 45 e 51 sono la priorità principale."},
"Offene Punkte:":{de:"Offene Punkte:",en:"Open items:",it:"Punti aperti:"},
"Handtücher Zi. 48, Milch nachbestellen, Schlüssel Zi. 46 übergeben.":{de:"Handtücher Zi. 48, Milch nachbestellen, Schlüssel Zi. 46 übergeben.",en:"Deliver towels to room 48, reorder milk, and hand over the key for room 46.",it:"Consegnare gli asciugamani alla camera 48, riordinare il latte e consegnare la chiave della camera 46."},
"Personalhinweis:":{de:"Personalhinweis:",en:"Staff note:",it:"Nota sul personale:"},
"Frühstücksvertretung noch ungeklärt.":{de:"Frühstücksvertretung noch ungeklärt.",en:"Breakfast shift coverage has not yet been arranged.",it:"La sostituzione per il turno della colazione non è ancora stata organizzata."},
"✨ Neue Übergabe mit KI ausfüllen":{de:"✨ Neue Übergabe mit KI ausfüllen",en:"✨ Create a new handover with AI",it:"✨ Crea una nuova consegna con l’IA"},
"📅 Übergaben-Verlauf":{de:"📅 Übergaben-Verlauf",en:"📅 Handover history",it:"📅 Cronologia consegne"},
"Alle →":{de:"Alle →",en:"All →",it:"Tutte →"},
"📋 Alle Übergaben verwalten":{de:"📋 Alle Übergaben verwalten",en:"📋 Manage all handovers",it:"📋 Gestisci tutte le consegne"},
"← Übergaben":{de:"← Übergaben",en:"← Handovers",it:"← Consegne"},
"Alle":{de:"Alle",en:"All",it:"Tutte"},"Offen":{de:"Offen",en:"Open",it:"Aperta"},"Erledigt":{de:"Erledigt",en:"Completed",it:"Completata"},
"alle":{de:"alle",en:"all",it:"tutte"},"offen":{de:"offen",en:"open",it:"aperta"},"erledigt":{de:"erledigt",en:"completed",it:"completata"},
"+ Übergabe erstellen":{de:"+ Übergabe erstellen",en:"+ Create handover",it:"+ Crea consegna"},
"Titel":{de:"Titel",en:"Title",it:"Titolo"},"Ersteller":{de:"Ersteller",en:"Creator",it:"Autore"},"Abteilungen":{de:"Abteilungen",en:"Departments",it:"Reparti"},"Datum":{de:"Datum",en:"Date",it:"Data"},"Aktionen":{de:"Aktionen",en:"Actions",it:"Azioni"},
"Bestimmte Abteilungen":{de:"Bestimmte Abteilungen",en:"Selected departments",it:"Reparti selezionati"},"Nur ich":{de:"Nur ich",en:"Only me",it:"Solo io"},
"Tägliche Übergabe Reception":{de:"Tägliche Übergabe Reception",en:"Daily reception handover",it:"Consegna giornaliera reception"},
"SEO nach Fragen suchen":{de:"SEO nach Fragen suchen",en:"Research SEO questions",it:"Ricerca domande SEO"},
"Inhalt":{de:"Inhalt",en:"Content",it:"Contenuto"},"Sichtbarkeit":{de:"Sichtbarkeit",en:"Visibility",it:"Visibilità"},"Tags":{de:"Tags",en:"Tags",it:"Tag"},
"Vorlage":{de:"Vorlage",en:"Template",it:"Modello"},"Beschreibung":{de:"Beschreibung",en:"Description",it:"Descrizione"},
"Vorlage wählen...":{de:"Vorlage wählen...",en:"Choose a template...",it:"Scegli un modello..."},
"Tägliche Reception-Übergabe":{de:"Tägliche Reception-Übergabe",en:"Daily reception handover",it:"Consegna giornaliera reception"},
"Wochenend-Übergabe Service":{de:"Wochenend-Übergabe Service",en:"Weekend service handover",it:"Consegna servizio weekend"},
"🌐 Schreib einfach in deiner Sprache – andere Mitarbeiter sehen automatisch ihre eigene Version.":{de:"🌐 Schreib einfach in deiner Sprache – andere Mitarbeiter sehen automatisch ihre eigene Version.",en:"🌐 Write in your own language – other employees will automatically see their translated version.",it:"🌐 Scrivi nella tua lingua – gli altri dipendenti vedranno automaticamente la versione tradotta."},
"Alle (hotelweit)":{de:"Alle (hotelweit)",en:"Everyone (hotel-wide)",it:"Tutti (intero hotel)"},
"Speichern":{de:"Speichern",en:"Save",it:"Salva"},"Als Entwurf speichern":{de:"Als Entwurf speichern",en:"Save as draft",it:"Salva come bozza"},"💾 Als Vorlage speichern":{de:"💾 Als Vorlage speichern",en:"💾 Save as template",it:"💾 Salva come modello"},
"✓ Als erledigt markieren":{de:"✓ Als erledigt markieren",en:"✓ Mark as completed",it:"✓ Segna come completata"},"✏️ Bearbeiten":{de:"✏️ Bearbeiten",en:"✏️ Edit",it:"✏️ Modifica"},"📌 Anpinnen":{de:"📌 Anpinnen",en:"📌 Pin",it:"📌 Fissa"}
};
function useHandoverTranslation(locale:UiLocale){useEffect(()=>{const translate=()=>{const root=document.querySelector("main");if(!root)return;const walker=document.createTreeWalker(root,NodeFilter.SHOW_TEXT);let node:Node|null;while((node=walker.nextNode())){const raw=node.textContent??"",key=raw.trim();for(const values of Object.values(translations)){if(Object.values(values).includes(key)){const next=values[locale];if(key!==next)node.textContent=raw.replace(key,next);break}}}root.querySelectorAll<HTMLInputElement|HTMLTextAreaElement>("input[placeholder],textarea[placeholder]").forEach(el=>{const placeholders:{[key:string]:Record<UiLocale,string>}={"🔍 Suchen...":{de:"🔍 Suchen...",en:"🔍 Search...",it:"🔍 Cerca..."},"Titel der Übergabe":{de:"Titel der Übergabe",en:"Handover title",it:"Titolo della consegna"},"Inhalt der Übergabe...":{de:"Inhalt der Übergabe...",en:"Handover content...",it:"Contenuto della consegna..."},"Tag hinzufügen (Enter)":{de:"Tag hinzufügen (Enter)",en:"Add tag (Enter)",it:"Aggiungi tag (Invio)"}};for(const values of Object.values(placeholders))if(Object.values(values).includes(el.placeholder))el.placeholder=values[locale]})};translate();const observer=new MutationObserver(translate);const root=document.querySelector("main");if(root)observer.observe(root,{childList:true,subtree:true});return()=>observer.disconnect()},[locale])}
function Title({children}:{children:ReactNode}){return <h1 className="mb-3 text-xs font-bold uppercase tracking-[.6px] text-[var(--qf-text-muted)]">{children}</h1>}function Head({children,action}:{children:ReactNode;action?:ReactNode}){return <header className="flex items-center justify-between gap-3 border-b px-4 py-3.5 text-[13px] font-bold">{children}{action}</header>}function Badge({children}:{children:ReactNode}){return <span className="rounded-full border border-[#e8d5a0] bg-[var(--qf-accent-soft)] px-2.5 py-1 text-[10.5px] font-bold text-[var(--qf-accent)]">{children}</span>}function Pill({status}:{status:Status}){return <span className={`rounded-full px-2 py-1 text-[9px] font-bold uppercase ${status==="erledigt"?"bg-green-100 text-green-700":"bg-blue-100 text-blue-700"}`}>{status}</span>}function Block({title,children}:{title:string;children:ReactNode}){return <div className="mb-3"><h3 className="mb-1.5 text-[10.5px] font-bold uppercase text-[var(--qf-text-muted)]">{title}</h3><div className="text-[13px] leading-6">{children}</div></div>}function Guest({room,children}:{room:string;children:ReactNode}){return <div className="mb-1 flex gap-2 rounded-md bg-[var(--qf-background)] p-2 text-xs"><span className="h-fit shrink-0 rounded bg-[var(--qf-border)] px-1.5 text-[10px] font-bold">{room}</span>{children}</div>}function Pending({title,meta,text}:{title:string;meta:string;text:string}){return <article className={`${card} mb-3 p-4 opacity-60`}><div className="mb-2 flex flex-wrap gap-2"><span className="rounded-full border bg-gray-100 px-2.5 py-1 text-[10.5px] font-bold">{title}</span><span className="text-[11px] text-[var(--qf-text-muted)] sm:ml-auto">{meta}</span></div><p className="text-xs text-[var(--qf-text-muted)]">{text}</p></article>}function Field({label,children}:{label:string;children:ReactNode}){return <label className="block text-xs font-semibold"><span className="mb-1.5 block">{label}</span>{children}</label>}
