import QRCode from "qrcode";
import { NextResponse } from "next/server";
import { getSessionUserId } from "../../../../lib/auth/session";
import { decryptSecret, encryptSecret, generateRecoveryCodes, generateTotpSecret, hashRecoveryCode, otpauthUri, verifyTotp } from "../../../../lib/auth/two-factor";
import { prisma } from "../../../../lib/prisma";
import { recordAuditLog } from "../../../../lib/audit/audit-service";

async function user(){const id=await getSessionUserId();return id?prisma.user.findFirst({where:{id,isActive:true,isDeleted:false},select:{id:true,email:true,hotelTenantId:true,twoFactorEnabled:true,twoFactorSecret:true,twoFactorRecoveryCodes:true}}):null}
export async function GET(){const current=await user();return current?NextResponse.json({enabled:current.twoFactorEnabled}):NextResponse.json({error:"UNAUTHENTICATED"},{status:401})}
export async function POST(request:Request){const current=await user();if(!current)return NextResponse.json({error:"UNAUTHENTICATED"},{status:401});const body=await request.json().catch(()=>null),action=body?.action;
 if(action==="setup"){if(current.twoFactorEnabled)return NextResponse.json({error:"ALREADY_ENABLED"},{status:409});const secret=generateTotpSecret(),uri=otpauthUri(secret,current.email),qrCode=await QRCode.toDataURL(uri,{width:240,margin:1,errorCorrectionLevel:"M"});return NextResponse.json({secret,qrCode})}
 if(action==="enable"){const secret=typeof body?.secret==="string"?body.secret:"",code=typeof body?.code==="string"?body.code:"";if(!secret||!verifyTotp(secret,code))return NextResponse.json({error:"INVALID_CODE"},{status:400});const recoveryCodes=generateRecoveryCodes();await prisma.$transaction(async tx=>{await tx.user.update({where:{id:current.id},data:{twoFactorEnabled:true,twoFactorSecret:encryptSecret(secret),twoFactorRecoveryCodes:recoveryCodes.map(hashRecoveryCode),twoFactorEnabledAt:new Date()}});await recordAuditLog(tx,{hotelTenantId:current.hotelTenantId,actorId:current.id,action:"STATUS_CHANGE",entityType:"USER",entityId:current.id,changes:{field:"twoFactorEnabled",before:false,after:true}})});return NextResponse.json({success:true,recoveryCodes})}
 if(action==="disable"){const code=typeof body?.code==="string"?body.code:"";if(!current.twoFactorEnabled||!current.twoFactorSecret)return NextResponse.json({error:"NOT_ENABLED"},{status:409});const hashes=Array.isArray(current.twoFactorRecoveryCodes)?current.twoFactorRecoveryCodes.filter((v):v is string=>typeof v==="string"):[],recoveryHash=hashRecoveryCode(code),recoveryIndex=hashes.indexOf(recoveryHash),valid=verifyTotp(decryptSecret(current.twoFactorSecret),code)||recoveryIndex>=0;if(!valid)return NextResponse.json({error:"INVALID_CODE"},{status:400});await prisma.$transaction(async tx=>{await tx.user.update({where:{id:current.id},data:{twoFactorEnabled:false,twoFactorSecret:null,twoFactorRecoveryCodes:[],twoFactorEnabledAt:null}});await recordAuditLog(tx,{hotelTenantId:current.hotelTenantId,actorId:current.id,action:"STATUS_CHANGE",entityType:"USER",entityId:current.id,changes:{field:"twoFactorEnabled",before:true,after:false}})});return NextResponse.json({success:true})}
 return NextResponse.json({error:"INVALID_ACTION"},{status:400})}
