"use client";

import { useCallback, useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { AppShell } from "../../../components/dashboard/app-shell";
import { useI18n } from "../../../components/i18n/i18n-provider";
import { BrandLoader } from "../../../components/ui/brand-loader";
import { getKnowledgeMessages } from "../../../lib/i18n/knowledge-messages";

type Department = { id: string; nameEn: string; nameDe: string; nameIt: string; mcpDepartmentId: string | null };
type VectorStore = { id: string; name: string; department?: { id?: string; name?: string } };

export default function KnowledgePage() {
  const { locale } = useI18n(); const router = useRouter(); const t = getKnowledgeMessages(locale);
  const copy = locale === "de" ? { add: "Wissensbasis hinzufügen", name: "Name", selectDepartment: "Abteilung auswählen", create: "Erstellen", cancel: "Abbrechen", loading: "Wissensbasen werden geladen…", deleteConfirm: "Diese Wissensbasis wirklich löschen?", created: "Wissensbasis erstellt.", deleted: "Wissensbasis gelöscht.", required: "Name und Abteilung sind erforderlich.", unsynced: "Diese Abteilung ist noch nicht mit MCP synchronisiert.", failed: "Die Anfrage ist fehlgeschlagen." } : locale === "it" ? { add: "Aggiungi base di conoscenza", name: "Nome", selectDepartment: "Seleziona reparto", create: "Crea", cancel: "Annulla", loading: "Caricamento delle basi di conoscenza…", deleteConfirm: "Eliminare questa base di conoscenza?", created: "Base di conoscenza creata.", deleted: "Base di conoscenza eliminata.", required: "Nome e reparto sono obbligatori.", unsynced: "Questo reparto non è ancora sincronizzato con MCP.", failed: "Richiesta non riuscita." } : { add: "Add knowledge base", name: "Name", selectDepartment: "Select department", create: "Create", cancel: "Cancel", loading: "Loading knowledge bases…", deleteConfirm: "Delete this knowledge base?", created: "Knowledge base created.", deleted: "Knowledge base deleted.", required: "Name and department are required.", unsynced: "This department is not synchronized with MCP yet.", failed: "The request failed." };
  const [stores, setStores] = useState<VectorStore[]>([]); const [departments, setDepartments] = useState<Department[]>([]); const [loading, setLoading] = useState(true); const [modal, setModal] = useState(false); const [name, setName] = useState(""); const [departmentId, setDepartmentId] = useState(""); const [saving, setSaving] = useState(false); const [notice, setNotice] = useState("");
  const load = useCallback(async () => { const response = await fetch("/api/settings/knowledge/vector-stores", { cache: "no-store" }); const data = await response.json(); if (!response.ok) throw new Error(data.message || copy.failed); setStores(Array.isArray(data.stores) ? data.stores : []); setDepartments(Array.isArray(data.departments) ? data.departments : []); }, [copy.failed]);
  useEffect(() => { let active = true; fetch("/api/settings/knowledge/vector-stores", { cache: "no-store" }).then(async response => { const data = await response.json(); if (!response.ok) throw new Error(data.message || copy.failed); return data; }).then(data => { if (active) { setStores(Array.isArray(data.stores) ? data.stores : []); setDepartments(Array.isArray(data.departments) ? data.departments : []); } }).catch((error: unknown) => { if (active) setNotice(error instanceof Error ? error.message : copy.failed); }).finally(() => { if (active) setLoading(false); }); return () => { active = false; }; }, [copy.failed]);
  const departmentName = (department: Department) => locale === "de" ? department.nameDe : locale === "it" ? department.nameIt : department.nameEn;
  async function createStore() { const selected = departments.find(department => department.id === departmentId); if (!name.trim() || !selected) { setNotice(copy.required); return; } if (!selected.mcpDepartmentId) { setNotice(copy.unsynced); return; } setSaving(true); setNotice(""); try { const response = await fetch("/api/settings/knowledge/vector-stores", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ name: name.trim(), departmentId }) }); const data = await response.json(); if (!response.ok) throw new Error(data.message || copy.failed); await load(); setModal(false); setName(""); setDepartmentId(""); setNotice(copy.created); } catch (error) { setNotice(error instanceof Error ? error.message : copy.failed); } finally { setSaving(false); } }
  async function deleteStore(store: VectorStore) { if (!window.confirm(copy.deleteConfirm) || saving) return; setSaving(true); setNotice(""); try { const response = await fetch(`/api/settings/knowledge/vector-stores?id=${encodeURIComponent(store.id)}`, { method: "DELETE" }); const data = await response.json(); if (!response.ok) throw new Error(data.message || copy.failed); setStores(items => items.filter(item => item.id !== store.id)); setNotice(copy.deleted); } catch (error) { setNotice(error instanceof Error ? error.message : copy.failed); } finally { setSaving(false); } }
  return <AppShell activeItem="settings" pageTitle={t.knowledgeTitle}><main className="p-4 sm:p-5 lg:px-7 lg:py-6">
    <button type="button" onClick={() => router.push("/settings")} className="mb-4 cursor-pointer text-[12.5px] font-semibold text-[var(--qf-text-muted)] hover:text-[var(--qf-accent)]">← {t.settings}</button>
    <p className="mb-5 max-w-4xl text-xs leading-[1.6] text-[var(--qf-text-muted)]">{t.knowledgeIntro}</p>{notice ? <p role="status" className="mb-4 rounded-md bg-[var(--qf-accent-soft)] px-3 py-2 text-xs text-[var(--qf-text)]">{notice}</p> : null}
    {!loading ? <section className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">{stores.map(store => <article key={store.id} role="link" tabIndex={0} onClick={() => router.push(`/settings/knowledge/${encodeURIComponent(store.id)}`)} onKeyDown={event => { if (event.key === "Enter" || event.key === " ") router.push(`/settings/knowledge/${encodeURIComponent(store.id)}`); }} className="flex min-h-[74px] cursor-pointer items-center justify-between rounded-lg border border-[var(--qf-border)] bg-white px-4 py-3.5 transition hover:border-[var(--qf-accent)]"><div className="min-w-0"><h2 className="truncate text-[13.5px] font-semibold">{store.name}</h2><p className="mt-0.5 text-[11.5px] text-[var(--qf-text-light)]">{store.department?.name || t.department}</p></div><button type="button" onClick={event => { event.stopPropagation(); void deleteStore(store); }} onKeyDown={event => event.stopPropagation()} aria-label={`${t.remove}: ${store.name}`} className="flex h-7 w-7 shrink-0 cursor-pointer items-center justify-center rounded-md border border-[var(--qf-border)] hover:border-[var(--qf-danger)]">🗑️</button></article>)}<button type="button" onClick={() => setModal(true)} className="flex min-h-[74px] cursor-pointer items-center justify-center rounded-lg border-2 border-dashed border-[var(--qf-border)] text-[13px] font-semibold text-[var(--qf-text-light)] hover:border-[var(--qf-accent)] hover:text-[var(--qf-accent)]">+ {copy.add}</button></section> : null}
    {modal ? <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/40 p-4" role="dialog" aria-modal="true"><div className="w-full max-w-md rounded-xl bg-white p-5 shadow-xl"><h2 className="text-sm font-bold">{copy.add}</h2><label className="mt-4 block text-xs font-semibold">{copy.name}<input value={name} onChange={event => setName(event.target.value)} className="mt-1.5 h-10 w-full rounded-lg border border-[var(--qf-border)] px-3 text-xs" /></label><label className="mt-4 block text-xs font-semibold">{copy.selectDepartment}<select value={departmentId} onChange={event => setDepartmentId(event.target.value)} className="mt-1.5 h-10 w-full rounded-lg border border-[var(--qf-border)] bg-white px-3 text-xs"><option value="">-- {copy.selectDepartment} --</option>{departments.map(department => <option key={department.id} value={department.id} disabled={!department.mcpDepartmentId}>{departmentName(department)}{!department.mcpDepartmentId ? " (MCP not synced)" : ""}</option>)}</select></label><div className="mt-5 flex justify-end gap-2"><button type="button" disabled={saving} onClick={() => setModal(false)} className="h-9 rounded-lg border border-[var(--qf-border)] px-4 text-xs font-semibold">{copy.cancel}</button><button type="button" disabled={saving} onClick={() => void createStore()} className="h-9 rounded-lg bg-[var(--qf-accent)] px-4 text-xs font-semibold text-white disabled:opacity-60">{copy.create}</button></div></div></div> : null}
    {loading || saving ? <BrandLoader label={copy.loading} overlay /> : null}
  </main></AppShell>;
}
