"use client";

import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { AppShell } from "../../../components/dashboard/app-shell";
import { BrandLoader } from "../../../components/ui/brand-loader";
import { useI18n } from "../../../components/i18n/i18n-provider";

type Provider = "openai" | "deepseek" | "perplexity" | "brevo" | "claude";
type Credential = { hasKey?: boolean; last4?: string; label?: string; baseUrl?: string; updatedAt?: string };
type ProviderState = { provider: Provider; isEnabled: boolean; defaultModel: string };
type Status = { active: boolean; hotelId: string | null; userEmail: string | null; departmentId: string | null; credentials?: Partial<Record<Provider, Credential>>; providerStates?: ProviderState[] };
const providerNames: Record<Provider, string> = { openai: "OpenAI", deepseek: "DeepSeek", perplexity: "Perplexity", brevo: "Brevo", claude: "Claude" };
const providers = Object.keys(providerNames) as Provider[];
const modelOptions = { openai: ["gpt-5", "gpt-5-mini", "gpt-5-nano", "gpt-4o-mini", "gpt-4o", "gpt-3.5-turbo"], deepseek: ["deepseek-chat", "deepseek-coder", "deepseek-reasoner"], perplexity: ["sonar", "sonar-deep-research", "sonar-reasoning-pro"], claude: ["claude-sonnet-4-5", "claude-haiku-4-5", "claude-opus-4-5", "claude-opus-4-1"] } as const;
type AiProvider = keyof typeof modelOptions;
const copy = {
  en: { title: "MCP integrations", settings: "Settings", info: "MCP connects QualityFriend securely with external services and gives the AI access to approved tools and hotel data. Once connected, available MCP services can be configured and used throughout QualityFriend.", heading: "QualityFriend MCP", description: "Connect your hotel to the QualityFriend MCP service. This creates a secure hotel workspace and service user for AI integrations.", online: "Online", offline: "Not connected", connect: "Connect with MCP", connecting: "Connecting…", connected: "MCP is active and ready to use.", failed: "MCP could not be connected. Please try again.", account: "Service account" },
  de: { title: "MCP-Integrationen", settings: "Einstellungen", info: "MCP verbindet QualityFriend sicher mit externen Diensten und ermöglicht der KI den Zugriff auf freigegebene Werkzeuge und Hoteldaten. Nach der Verbindung können verfügbare MCP-Dienste in QualityFriend konfiguriert und verwendet werden.", heading: "QualityFriend MCP", description: "Verbinden Sie Ihr Hotel mit dem QualityFriend-MCP-Dienst. Dabei werden ein sicherer Hotel-Arbeitsbereich und ein Dienstbenutzer für KI-Integrationen erstellt.", online: "Online", offline: "Nicht verbunden", connect: "Mit MCP verbinden", connecting: "Verbindung wird hergestellt…", connected: "MCP ist aktiv und einsatzbereit.", failed: "MCP konnte nicht verbunden werden. Bitte versuchen Sie es erneut.", account: "Dienstkonto" },
  it: { title: "Integrazioni MCP", settings: "Impostazioni", info: "MCP collega QualityFriend in modo sicuro ai servizi esterni e consente all'IA di accedere agli strumenti approvati e ai dati dell'hotel. Dopo la connessione, i servizi MCP disponibili possono essere configurati e utilizzati in QualityFriend.", heading: "QualityFriend MCP", description: "Collega il tuo hotel al servizio MCP di QualityFriend. Verranno creati uno spazio hotel sicuro e un utente di servizio per le integrazioni IA.", online: "Online", offline: "Non connesso", connect: "Connetti con MCP", connecting: "Connessione…", connected: "MCP è attivo e pronto all'uso.", failed: "Impossibile connettere MCP. Riprova.", account: "Account di servizio" },
} as const;

export default function McpSettingsPage() {
  const { locale } = useI18n(); const router = useRouter(); const t = copy[locale];
  const [status, setStatus] = useState<Status | null>(null); const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const [keys, setKeys] = useState<Partial<Record<Provider, string>>>({}); const [savingProvider, setSavingProvider] = useState<Provider | null>(null); const [providerSettings, setProviderSettings] = useState<Record<AiProvider, { isEnabled: boolean; defaultModel: string }>>({ openai: { isEnabled: false, defaultModel: "gpt-5-mini" }, deepseek: { isEnabled: false, defaultModel: "deepseek-chat" }, perplexity: { isEnabled: false, defaultModel: "sonar" }, claude: { isEnabled: false, defaultModel: "claude-sonnet-4-5" } });
  function applyStatus(data: Status) { setStatus(data); setProviderSettings((current) => { const next = { ...current }; for (const state of data.providerStates || []) if (state.provider in modelOptions) next[state.provider as AiProvider] = { isEnabled: state.isEnabled, defaultModel: state.defaultModel || current[state.provider as AiProvider].defaultModel }; return next; }); }
  useEffect(() => { fetch("/api/settings/mcp").then(async (response) => { if (response.status === 401) return router.replace("/login"); if (!response.ok) throw new Error(); applyStatus(await response.json()); }).catch(() => setError(t.failed)); }, [router, t.failed]);
  async function connect() {
    setBusy(true); setError("");
    try { const response = await fetch("/api/settings/mcp", { method: "POST" }); const data = await response.json(); if (!response.ok) throw new Error(typeof data.message === "string" ? data.message : t.failed); setStatus(data); }
    catch (caught) { setError(caught instanceof Error ? caught.message : t.failed); }
    finally { setBusy(false); }
  }
  async function saveCredential(provider: Provider) {
    const apiKey = keys[provider]?.trim(); if (!apiKey) return;
    setSavingProvider(provider); setError("");
    try { const response = await fetch("/api/settings/mcp", { method: "PUT", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ provider, apiKey }) }); const data = await response.json(); if (!response.ok) throw new Error(typeof data.message === "string" ? data.message : t.failed); setKeys((current) => ({ ...current, [provider]: "" })); const refreshed = await fetch("/api/settings/mcp"); if (refreshed.ok) setStatus(await refreshed.json()); }
    catch (caught) { setError(caught instanceof Error ? caught.message : t.failed); }
    finally { setSavingProvider(null); }
  }
  async function saveProvider(provider: AiProvider) {
    setSavingProvider(provider); setError(""); const setting = providerSettings[provider];
    try { const response = await fetch("/api/settings/mcp", { method: "PUT", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ type: "provider", provider, ...setting }) }); const data = await response.json(); if (!response.ok) throw new Error(typeof data.message === "string" ? data.message : t.failed); }
    catch (caught) { setError(caught instanceof Error ? caught.message : t.failed); }
    finally { setSavingProvider(null); }
  }
  return <AppShell activeItem="settings" pageTitle={t.title}><main className="p-4 sm:p-5 lg:px-7 lg:py-6">
    <button type="button" onClick={() => router.push("/settings")} className="mb-5 cursor-pointer text-[12.5px] font-semibold text-[var(--qf-text-muted)] hover:text-[var(--qf-accent)]">← {t.settings}</button>
    <p className="mb-6 text-xs leading-[1.6] text-[var(--qf-text-muted)]">{t.info}</p>
    {!status && !error ? <BrandLoader label={t.connecting} /> : <section className="w-full overflow-hidden rounded-[var(--qf-radius)] border border-[var(--qf-border)] bg-white shadow-[var(--qf-shadow)]">
      <div className="flex flex-col gap-5 border-b border-[var(--qf-border)] p-5 sm:flex-row sm:items-start sm:justify-between sm:p-7">
        <div className="flex gap-4"><span className="flex h-12 w-12 shrink-0 items-center justify-center rounded-xl bg-[var(--qf-accent-soft)] text-2xl" aria-hidden>🔌</span><div><h1 className="text-lg font-bold">{t.heading}</h1><p className="mt-1 max-w-xl text-[13px] leading-6 text-[var(--qf-text-muted)]">{t.description}</p></div></div>
        <span className={`inline-flex w-fit shrink-0 items-center gap-2 whitespace-nowrap rounded-full px-3 py-1.5 text-xs font-bold ${status?.active ? "bg-green-100 text-green-700" : "bg-slate-100 text-slate-600"}`}><span className={`h-2 w-2 shrink-0 rounded-full ${status?.active ? "bg-green-500 shadow-[0_0_0_3px_rgba(34,197,94,.15)]" : "bg-slate-400"}`} />{status?.active ? t.online : t.offline}</span>
      </div>
      <div className="p-5 sm:p-7">{error ? <p role="alert" className="mb-4 rounded-lg border border-red-200 bg-red-50 px-4 py-3 text-xs font-medium text-red-700">{error}</p> : null}{status?.active ? <div><p className="rounded-lg border border-green-200 bg-green-50 px-4 py-3 text-sm font-semibold text-green-700">✓ {t.connected}</p>{status.userEmail ? <p className="mt-4 break-all text-xs text-[var(--qf-text-muted)]"><span className="font-semibold text-[var(--qf-text)]">{t.account}:</span> {status.userEmail}</p> : null}</div> : <button type="button" disabled={busy} onClick={connect} className="min-h-11 w-full cursor-pointer rounded-lg bg-[var(--qf-accent)] px-5 text-sm font-bold text-white transition hover:opacity-90 disabled:cursor-wait disabled:opacity-60 sm:w-auto">{busy ? t.connecting : t.connect}</button>}</div>
    </section>}
    {status?.active ? <section className="mt-7"><div className="mb-3"><h2 className="text-[15px] font-bold">Provider credentials</h2><p className="mt-1 text-xs text-[var(--qf-text-muted)]">Add or replace API keys used by MCP. Saved keys are masked and cannot be viewed again.</p></div><div className="grid gap-3 lg:grid-cols-2">{providers.map((provider) => { const credential = status.credentials?.[provider], configured = credential?.hasKey === true; return <article key={provider} className="rounded-[var(--qf-radius)] border border-[var(--qf-border)] bg-white p-4 shadow-[var(--qf-shadow)] sm:p-5"><div className="mb-4 flex items-start justify-between gap-3"><div><h3 className="text-sm font-bold">{providerNames[provider]}</h3><p className="mt-1 text-[11px] text-[var(--qf-text-muted)]">{credential?.baseUrl || "API credential"}</p></div><span className={`shrink-0 rounded-full px-2.5 py-1 text-[10px] font-bold ${configured ? "bg-green-100 text-green-700" : "bg-slate-100 text-slate-600"}`}>{configured ? `Set ••••${credential.last4 || ""}` : "Not set"}</span></div><label className="block text-xs font-semibold"><span className="mb-1.5 block">{configured ? `Replace ${providerNames[provider]} API key` : `${providerNames[provider]} API key`}</span><input type="password" autoComplete="off" value={keys[provider] || ""} onChange={(event) => setKeys((current) => ({ ...current, [provider]: event.target.value }))} placeholder={`Enter ${providerNames[provider]} API key`} className="h-11 w-full rounded-lg border border-[var(--qf-border)] px-3.5 text-sm outline-none focus:border-[var(--qf-accent)]" /></label><button type="button" disabled={!keys[provider]?.trim() || savingProvider !== null} onClick={() => void saveCredential(provider)} className="mt-3 min-h-10 w-full cursor-pointer rounded-lg bg-[var(--qf-accent)] px-4 text-xs font-bold text-white disabled:cursor-not-allowed disabled:opacity-50 sm:w-auto">{savingProvider === provider ? "Saving…" : "Save credentials"}</button>{credential?.updatedAt ? <p className="mt-3 text-[10px] text-[var(--qf-text-light)]">Last updated: {new Date(credential.updatedAt).toLocaleString()}</p> : null}</article>; })}</div></section> : null}
    {status?.active ? <section className="mt-7"><div className="mb-3"><h2 className="text-[15px] font-bold">AI providers</h2><p className="mt-1 text-xs text-[var(--qf-text-muted)]">Enable a provider and choose the default model MCP should use.</p></div><div className="grid gap-3 lg:grid-cols-2">{(Object.keys(modelOptions) as AiProvider[]).map((provider) => { const setting = providerSettings[provider]; return <article key={provider} className="rounded-[var(--qf-radius)] border border-[var(--qf-border)] bg-white p-4 shadow-[var(--qf-shadow)] sm:p-5"><div className="mb-4 flex items-center justify-between gap-3"><h3 className="text-sm font-bold">{providerNames[provider]}</h3><label className="flex cursor-pointer items-center gap-2 text-xs font-semibold"><input type="checkbox" checked={setting.isEnabled} onChange={(event) => setProviderSettings((current) => ({ ...current, [provider]: { ...current[provider], isEnabled: event.target.checked } }))} className="h-4 w-4 accent-[var(--qf-accent)]" />Enabled</label></div><label className="block text-xs font-semibold"><span className="mb-1.5 block">Default model</span><select value={setting.defaultModel} onChange={(event) => setProviderSettings((current) => ({ ...current, [provider]: { ...current[provider], defaultModel: event.target.value } }))} className="h-11 w-full rounded-lg border border-[var(--qf-border)] bg-white px-3 text-sm">{modelOptions[provider].map((model) => <option key={model} value={model}>{model}</option>)}</select></label><button type="button" disabled={savingProvider !== null} onClick={() => void saveProvider(provider)} className="mt-3 min-h-10 w-full cursor-pointer rounded-lg border border-[var(--qf-accent)] px-4 text-xs font-bold text-[var(--qf-accent)] disabled:opacity-50 sm:w-auto">{savingProvider === provider ? "Saving…" : "Save provider"}</button></article>; })}</div></section> : null}
  </main></AppShell>;
}
