export const dictionaries = {
  en: {
    common: { language: "Language", brandSubtitle: "Hotel Operations", optional: "optional", underDevelopment: "Under development", required: "This field is required.", invalidEmail: "Enter a valid email address.", shortPassword: "Password must contain at least 8 characters.", acceptTerms: "You must accept the terms to continue.", add: "Add", edit: "Edit", save: "Save", cancel: "Cancel", nameEnglish: "Name in English", nameGerman: "Name in German", nameItalian: "Name in Italian" },
    login: {
      eyebrow: "Welcome back", heroTitle: "Your hotel. Your team. One system.", heroDescription: "Keep tasks, workflows, and your entire team in view from one central place.", title: "Sign in", subtitle: "Sign in with your QualityFriend account.", email: "Email address", password: "Password", passwordPlaceholder: "Your password", forgotPassword: "Forgot password?", remember: "Keep me signed in", submit: "Sign in", submitting: "Signing in...", error: "The email or password is incorrect.", noAccount: "No account yet?", register: "Create account", showPassword: "Show password", hidePassword: "Hide password",
    },
    register: {
      eyebrow: "Work better together", heroTitle: "A good workday starts with clarity.", heroDescription: "Set up your workspace and bring structure to your hotel's daily operations.", title: "Create account", subtitle: "Create your company and primary contact profile.", companySection: "Company details", contactSection: "Contact details", addressSection: "Business address", firstName: "First name", lastName: "Last name", company: "Company", hotelName: "Hotel name", email: "Email address", password: "Password", passwordPlaceholder: "At least 8 characters", showPassword: "Show password", hidePassword: "Hide password", contactPerson: "Contact person", phone: "Phone number", country: "Country", city: "City", street: "Street address", zip: "ZIP / Postal code", vatId: "VAT ID", terms: "I accept the Terms of Service and Privacy Policy.", submit: "Create account", submitting: "Creating account...", success: "Account created successfully. You can now sign in.", emailExists: "An account with this email already exists.", error: "Registration failed. Please check your details and try again.", hasAccount: "Already registered?", login: "Sign in",
    },
    navigation: { overview: "Overview", dashboard: "Dashboard", aiAssistant: "AI Assistant", new: "NEW", operations: "Operations", handovers: "Handovers", tasks: "Tasks & Checklists", housekeeping: "Housekeeping", repairs: "Repairs", notes: "Notes", staff: "Staff", schedule: "Schedule", recruiting: "Recruiting", manuals: "Manuals", strategy: "Strategy", budget: "Budget & Forecast", revenue: "AI Revenue Forecast", administration: "Administration", settings: "Settings", administrator: "Administrator" },
    dashboard: { greeting: "Good morning, Klaus", date: "Wednesday, 19 August 2026", report: "Report", addTask: "Add task", analysisTitle: "Daily analysis · Wednesday, 19 Aug", analysisBody: "10 arrivals and 6 departures today. Rooms 45 & 51 need express cleaning before 14:00. Breakfast cover is still unresolved. A new five-star Tripadvisor review is waiting for a reply.", discuss: "Discuss with AI", occupancy: "Occupancy", arrivals: "Arrivals / Departures", roomsReady: "Rooms ready", rating: "Average rating (30d)", vsWeek: "vs. last week", checkin: "Check-in from 15:00", open: "3 open", express: "Express by 14:00", reviews: "137 reviews", myTasks: "My tasks today", showAll: "Show all", task1: "Reply to the Tripadvisor review", task1Meta: "Reception · Due by 11:00", task2: "Confirm breakfast cover", task2Meta: "Management · Due by 10:00", task3: "Review room 45 express cleaning", task3Meta: "Housekeeping · Due by 14:00", weather: "Changeable · Ritten", rain: "Rain from 16:00", wind: "Wind 12 km/h", uv: "UV index 4", dirty: "Dirty", cleaning: "Cleaning", ready: "Ready", inspected: "Inspected", hkNote: "Rooms 45 & 51 express priority until 14:00 · Room 50 no service", onDuty: "On duty today", roster: "Schedule", teamSummary: "7 employees · 1 absent", vacation: "Vacation" },
    settings: { usersTeams: "Users & Teams", manageUsers: "Manage users", manageUsersDescription: "Activate, edit, and deactivate employees", manageTeams: "Manage teams", manageTeamsDescription: "Create, edit, and delete teams", manageDepartments: "Manage departments", manageDepartmentsDescription: "Create, edit, and delete departments", roles: "Roles & access rights", rolesDescription: "Control who can see each module", aiKnowledge: "AI & Knowledge Base", knowledge: "Manage knowledge base", knowledgeDescription: "Store documents by department or for the whole hotel", training: "Training files (fine-tuning)", trainingDescription: "Additional training data for the AI", general: "General", defaultLanguage: "Hotel default language", defaultLanguageDescription: "Fallback language for the interface", recycleBin: "Recycle bin", recycleBinDescription: "Restore deleted entries", activityLog: "Activity log", activityLogDescription: "See who changed what and when", departments: "Departments", teams: "Teams", employees: "employees", employee: "employee", members: "members", member: "member", addDepartment: "Add department", addTeam: "Add team", edit: "Edit", delete: "Delete", reception: "Reception", kitchen: "Kitchen", maintenance: "Maintenance", administration: "Administration", frontOfficeTeam: "Front Office", morningTeam: "Morning shift", serviceTeam: "Service team", managementTeam: "Management" },
  },
  de: {
    common: { language: "Sprache", brandSubtitle: "Hotelbetrieb", optional: "optional", underDevelopment: "In Entwicklung", required: "Dieses Feld ist erforderlich.", invalidEmail: "Geben Sie eine gültige E-Mail-Adresse ein.", shortPassword: "Das Passwort muss mindestens 8 Zeichen enthalten.", acceptTerms: "Sie müssen die Bedingungen akzeptieren.", add: "Hinzufügen", edit: "Bearbeiten", save: "Speichern", cancel: "Abbrechen", nameEnglish: "Name auf Englisch", nameGerman: "Name auf Deutsch", nameItalian: "Name auf Italienisch" },
    login: {
      eyebrow: "Willkommen zurück", heroTitle: "Ihr Hotel. Ihr Team. Ein System.", heroDescription: "Behalten Sie Aufgaben, Abläufe und Ihr gesamtes Team an einem zentralen Ort im Blick.", title: "Anmelden", subtitle: "Melden Sie sich mit Ihrem QualityFriend-Konto an.", email: "E-Mail-Adresse", password: "Passwort", passwordPlaceholder: "Ihr Passwort", forgotPassword: "Passwort vergessen?", remember: "Angemeldet bleiben", submit: "Anmelden", submitting: "Anmeldung läuft...", error: "E-Mail-Adresse oder Passwort ist falsch.", noAccount: "Noch kein Konto?", register: "Konto erstellen", showPassword: "Passwort anzeigen", hidePassword: "Passwort ausblenden",
    },
    register: {
      eyebrow: "Gemeinsam besser arbeiten", heroTitle: "Ein guter Arbeitstag beginnt mit Klarheit.", heroDescription: "Richten Sie Ihren Arbeitsbereich ein und bringen Sie Struktur in die täglichen Abläufe Ihres Hotels.", title: "Konto erstellen", subtitle: "Legen Sie Ihr Unternehmen und den Hauptkontakt an.", companySection: "Unternehmensdaten", contactSection: "Kontaktdaten", addressSection: "Geschäftsadresse", firstName: "Vorname", lastName: "Nachname", company: "Unternehmen", hotelName: "Hotelname", email: "E-Mail-Adresse", password: "Passwort", passwordPlaceholder: "Mindestens 8 Zeichen", showPassword: "Passwort anzeigen", hidePassword: "Passwort ausblenden", contactPerson: "Ansprechperson", phone: "Telefonnummer", country: "Land", city: "Stadt", street: "Straße und Hausnummer", zip: "PLZ", vatId: "USt-IdNr.", terms: "Ich akzeptiere die Nutzungsbedingungen und die Datenschutzerklärung.", submit: "Konto erstellen", submitting: "Konto wird erstellt...", success: "Konto erfolgreich erstellt. Sie können sich jetzt anmelden.", emailExists: "Für diese E-Mail-Adresse besteht bereits ein Konto.", error: "Registrierung fehlgeschlagen. Bitte prüfen Sie Ihre Angaben.", hasAccount: "Bereits registriert?", login: "Jetzt anmelden",
    },
    navigation: { overview: "Übersicht", dashboard: "Dashboard", aiAssistant: "KI-Assistent", new: "NEU", operations: "Betrieb", handovers: "Übergaben", tasks: "Aufgaben & Checklisten", housekeeping: "Housekeeping", repairs: "Reparaturen", notes: "Notizen", staff: "Personal", schedule: "Dienstplan", recruiting: "Recruiting", manuals: "Handbücher", strategy: "Strategie", budget: "Budget & Forecast", revenue: "AI Revenue Forecast", administration: "Verwaltung", settings: "Einstellungen", administrator: "Administrator" },
    dashboard: { greeting: "Guten Morgen, Klaus", date: "Mittwoch, 19. August 2026", report: "Melden", addTask: "Aufgabe", analysisTitle: "Tagesanalyse · Mittwoch, 19. Aug", analysisBody: "Heute 10 Ankünfte und 6 Abgänge. Zimmer 45 & 51 brauchen Express-Reinigung vor 14:00. Die Frühstücksvertretung ist noch ungeregelt. Eine neue Fünf-Sterne-Tripadvisor-Rezension wartet auf Antwort.", discuss: "Mit KI besprechen", occupancy: "Auslastung", arrivals: "Ankünfte / Abgänge", roomsReady: "Zimmer bereit", rating: "Ø Bewertung (30T)", vsWeek: "vs. Vorwoche", checkin: "Check-in ab 15:00 Uhr", open: "3 offen", express: "Express bis 14:00", reviews: "137 Bewertungen", myTasks: "Meine Aufgaben heute", showAll: "Alle anzeigen", task1: "Tripadvisor-Rezension beantworten", task1Meta: "Rezeption · Fällig bis 11:00", task2: "Frühstücksvertretung bestätigen", task2Meta: "Management · Fällig bis 10:00", task3: "Express-Reinigung Zimmer 45 prüfen", task3Meta: "Housekeeping · Fällig bis 14:00", weather: "Wechselhaft · Ritten", rain: "Regen ab 16:00", wind: "Wind 12 km/h", uv: "UV-Index 4", dirty: "Schmutzig", cleaning: "Reinigung", ready: "Bereit", inspected: "Inspiziert", hkNote: "Zi. 45 & 51 Express-Priorität bis 14:00 · Zi. 50 kein Service", onDuty: "Heute im Dienst", roster: "Dienstplan", teamSummary: "7 Mitarbeiter · 1 abwesend", vacation: "Urlaub" },
    settings: { usersTeams: "Benutzer & Teams", manageUsers: "Benutzer verwalten", manageUsersDescription: "Mitarbeiter aktivieren, bearbeiten und deaktivieren", manageTeams: "Teams verwalten", manageTeamsDescription: "Teams anlegen, bearbeiten und löschen", manageDepartments: "Abteilungen verwalten", manageDepartmentsDescription: "Abteilungen anlegen, bearbeiten und löschen", roles: "Rollen & Zugriffsrechte", rolesDescription: "Steuern, wer welches Modul sehen kann", aiKnowledge: "KI & Wissensbasis", knowledge: "Wissensbasis verwalten", knowledgeDescription: "Dokumente pro Abteilung oder hotelweit hinterlegen", training: "Trainingsdateien (Fine-Tuning)", trainingDescription: "Zusätzliche Trainingsdaten für die KI", general: "Allgemein", defaultLanguage: "Standardsprache Hotel", defaultLanguageDescription: "Fallback-Sprache der Oberfläche", recycleBin: "Papierkorb", recycleBinDescription: "Gelöschte Einträge wiederherstellen", activityLog: "Aktivitätsprotokoll", activityLogDescription: "Sehen, wer wann was geändert hat", departments: "Abteilungen", teams: "Teams", employees: "Mitarbeiter", employee: "Mitarbeiter", members: "Mitglieder", member: "Mitglied", addDepartment: "Abteilung hinzufügen", addTeam: "Team hinzufügen", edit: "Bearbeiten", delete: "Löschen", reception: "Rezeption", kitchen: "Küche", maintenance: "Haustechnik", administration: "Verwaltung", frontOfficeTeam: "Front Office", morningTeam: "Frühschicht", serviceTeam: "Service-Team", managementTeam: "Management" },
  },
  it: {
    common: { language: "Lingua", brandSubtitle: "Gestione alberghiera", optional: "facoltativo", underDevelopment: "In fase di sviluppo", required: "Questo campo è obbligatorio.", invalidEmail: "Inserisci un indirizzo e-mail valido.", shortPassword: "La password deve contenere almeno 8 caratteri.", acceptTerms: "Devi accettare i termini per continuare.", add: "Aggiungi", edit: "Modifica", save: "Salva", cancel: "Annulla", nameEnglish: "Nome in inglese", nameGerman: "Nome in tedesco", nameItalian: "Nome in italiano" },
    login: {
      eyebrow: "Bentornato", heroTitle: "Il tuo hotel. Il tuo team. Un unico sistema.", heroDescription: "Tieni sotto controllo attività, processi e tutto il team da un unico spazio centrale.", title: "Accedi", subtitle: "Accedi con il tuo account QualityFriend.", email: "Indirizzo e-mail", password: "Password", passwordPlaceholder: "La tua password", forgotPassword: "Password dimenticata?", remember: "Resta connesso", submit: "Accedi", submitting: "Accesso in corso...", error: "L'indirizzo e-mail o la password non sono corretti.", noAccount: "Non hai ancora un account?", register: "Crea account", showPassword: "Mostra password", hidePassword: "Nascondi password",
    },
    register: {
      eyebrow: "Lavorare meglio insieme", heroTitle: "Una buona giornata di lavoro inizia dalla chiarezza.", heroDescription: "Configura il tuo spazio di lavoro e organizza le attività quotidiane del tuo hotel.", title: "Crea account", subtitle: "Inserisci i dati dell'azienda e del contatto principale.", companySection: "Dati aziendali", contactSection: "Dati di contatto", addressSection: "Indirizzo aziendale", firstName: "Nome", lastName: "Cognome", company: "Azienda", hotelName: "Nome dell'hotel", email: "Indirizzo e-mail", password: "Password", passwordPlaceholder: "Almeno 8 caratteri", showPassword: "Mostra password", hidePassword: "Nascondi password", contactPerson: "Persona di contatto", phone: "Numero di telefono", country: "Paese", city: "Città", street: "Indirizzo", zip: "CAP", vatId: "Partita IVA", terms: "Accetto i Termini di servizio e l'Informativa sulla privacy.", submit: "Crea account", submitting: "Creazione account...", success: "Account creato correttamente. Ora puoi accedere.", emailExists: "Esiste già un account con questo indirizzo e-mail.", error: "Registrazione non riuscita. Controlla i dati e riprova.", hasAccount: "Hai già un account?", login: "Accedi",
    },
    navigation: { overview: "Panoramica", dashboard: "Dashboard", aiAssistant: "Assistente IA", new: "NUOVO", operations: "Operazioni", handovers: "Passaggi di consegne", tasks: "Attività e checklist", housekeeping: "Housekeeping", repairs: "Riparazioni", notes: "Note", staff: "Personale", schedule: "Turni", recruiting: "Selezione", manuals: "Manuali", strategy: "Strategia", budget: "Budget e previsioni", revenue: "Previsioni ricavi IA", administration: "Amministrazione", settings: "Impostazioni", administrator: "Amministratore" },
    dashboard: { greeting: "Buongiorno, Klaus", date: "Mercoledì, 19 agosto 2026", report: "Segnala", addTask: "Attività", analysisTitle: "Analisi giornaliera · Mercoledì 19 ago", analysisBody: "Oggi 10 arrivi e 6 partenze. Le camere 45 e 51 richiedono pulizia express prima delle 14:00. La sostituzione per la colazione non è ancora definita. Una nuova recensione Tripadvisor a cinque stelle attende risposta.", discuss: "Parla con l'IA", occupancy: "Occupazione", arrivals: "Arrivi / Partenze", roomsReady: "Camere pronte", rating: "Valutazione media (30g)", vsWeek: "rispetto alla settimana scorsa", checkin: "Check-in dalle 15:00", open: "3 aperte", express: "Express entro le 14:00", reviews: "137 recensioni", myTasks: "Le mie attività di oggi", showAll: "Mostra tutte", task1: "Rispondere alla recensione Tripadvisor", task1Meta: "Reception · Entro le 11:00", task2: "Confermare sostituzione colazione", task2Meta: "Direzione · Entro le 10:00", task3: "Verificare pulizia express camera 45", task3Meta: "Housekeeping · Entro le 14:00", weather: "Variabile · Renon", rain: "Pioggia dalle 16:00", wind: "Vento 12 km/h", uv: "Indice UV 4", dirty: "Sporche", cleaning: "In pulizia", ready: "Pronte", inspected: "Ispezionate", hkNote: "Camere 45 e 51 priorità express entro le 14:00 · Camera 50 nessun servizio", onDuty: "In servizio oggi", roster: "Turni", teamSummary: "7 dipendenti · 1 assente", vacation: "Ferie" },
    settings: { usersTeams: "Utenti e team", manageUsers: "Gestisci utenti", manageUsersDescription: "Attiva, modifica e disattiva i dipendenti", manageTeams: "Gestisci team", manageTeamsDescription: "Crea, modifica ed elimina i team", manageDepartments: "Gestisci reparti", manageDepartmentsDescription: "Crea, modifica ed elimina i reparti", roles: "Ruoli e diritti di accesso", rolesDescription: "Controlla chi può vedere ciascun modulo", aiKnowledge: "IA e base di conoscenza", knowledge: "Gestisci base di conoscenza", knowledgeDescription: "Archivia documenti per reparto o per tutto l'hotel", training: "File di addestramento (fine-tuning)", trainingDescription: "Dati di addestramento aggiuntivi per l'IA", general: "Generale", defaultLanguage: "Lingua predefinita dell'hotel", defaultLanguageDescription: "Lingua di fallback dell'interfaccia", recycleBin: "Cestino", recycleBinDescription: "Ripristina gli elementi eliminati", activityLog: "Registro attività", activityLogDescription: "Vedi chi ha modificato cosa e quando", departments: "Reparti", teams: "Team", employees: "dipendenti", employee: "dipendente", members: "membri", member: "membro", addDepartment: "Aggiungi reparto", addTeam: "Aggiungi team", edit: "Modifica", delete: "Elimina", reception: "Reception", kitchen: "Cucina", maintenance: "Manutenzione", administration: "Amministrazione", frontOfficeTeam: "Front Office", morningTeam: "Turno mattutino", serviceTeam: "Team di servizio", managementTeam: "Direzione" },
  },
} as const;

export type Locale = keyof typeof dictionaries;
export const supportedLocales = ["en", "de", "it"] as const;

export const requestMessages = {
  en: { loading: "Loading…", failed: "Something went wrong. Please try again.", nameExists: "This name already exists." },
  de: { loading: "Wird geladen…", failed: "Etwas ist schiefgelaufen. Bitte versuchen Sie es erneut.", nameExists: "Dieser Name existiert bereits." },
  it: { loading: "Caricamento…", failed: "Qualcosa è andato storto. Riprova.", nameExists: "Questo nome esiste già." },
} as const;

export const auditMessages = {
  en: { allUsers: "Showing activity from all hotel users.", onlyYou: "Showing only your activity.", empty: "No activity recorded yet.", filterDate: "Date", filterUser: "Hotel user", everyUser: "All users", actions: { CREATE: "created", UPDATE: "updated", DELETE: "deleted", STATUS_CHANGE: "changed status" }, entities: { DEPARTMENT: "department", TEAM: "team", HOTEL: "hotel", USER: "user" } },
  de: { allUsers: "Aktivitäten aller Hotelbenutzer werden angezeigt.", onlyYou: "Nur Ihre Aktivitäten werden angezeigt.", empty: "Noch keine Aktivität aufgezeichnet.", filterDate: "Datum", filterUser: "Hotelbenutzer", everyUser: "Alle Benutzer", actions: { CREATE: "erstellt", UPDATE: "aktualisiert", DELETE: "gelöscht", STATUS_CHANGE: "Status geändert" }, entities: { DEPARTMENT: "Abteilung", TEAM: "Team", HOTEL: "Hotel", USER: "Benutzer" } },
  it: { allUsers: "Sono visualizzate le attività di tutti gli utenti dell'hotel.", onlyYou: "Sono visualizzate solo le tue attività.", empty: "Nessuna attività registrata.", filterDate: "Data", filterUser: "Utente dell'hotel", everyUser: "Tutti gli utenti", actions: { CREATE: "ha creato", UPDATE: "ha aggiornato", DELETE: "ha eliminato", STATUS_CHANGE: "ha cambiato lo stato" }, entities: { DEPARTMENT: "reparto", TEAM: "team", HOTEL: "hotel", USER: "utente" } },
} as const;

export const settingsPageMessages = {
  en: { departmentsTeams: "Manage departments & teams", departmentsTeamsDescription: "Create, edit, and delete departments and teams" },
  de: { departmentsTeams: "Abteilungen & Teams verwalten", departmentsTeamsDescription: "Abteilungen und Teams anlegen, bearbeiten und löschen" },
  it: { departmentsTeams: "Gestisci reparti e team", departmentsTeamsDescription: "Crea, modifica ed elimina reparti e team" },
} as const;

export const recycleBinMessages = {
  en: { description: "Deleted items from this hotel can be restored here.", empty: "The recycle bin is empty.", restore: "Restore", deleted: "Deleted", types: { department: "Department", team: "Team", user: "User" } },
  de: { description: "Gelöschte Einträge dieses Hotels können hier wiederhergestellt werden.", empty: "Der Papierkorb ist leer.", restore: "Wiederherstellen", deleted: "Gelöscht", types: { department: "Abteilung", team: "Team", user: "Benutzer" } },
  it: { description: "Gli elementi eliminati di questo hotel possono essere ripristinati qui.", empty: "Il cestino è vuoto.", restore: "Ripristina", deleted: "Eliminato", types: { department: "Reparto", team: "Team", user: "Utente" } },
} as const;

export const hotelLanguageMessages = {
  en: { title: "Hotel default language", label: "Default language", save: "Save", cancel: "Cancel" },
  de: { title: "Standardsprache des Hotels", label: "Standardsprache", save: "Speichern", cancel: "Abbrechen" },
  it: { title: "Lingua predefinita dell'hotel", label: "Lingua predefinita", save: "Salva", cancel: "Annulla" },
} as const;

export const roleMessages = {
  en: { title: "Roles & access rights", roles: "Roles", chooseRole: "Choose a role to configure", configure: "Choose what this role can do", ownerLocked: "The owner always has full access", module: "Module", save: "Save changes", savedPreview: "UI changes saved for this preview.", roleNames: { OWNER: "Owner", ADMIN: "Administrator", USER: "User" }, roleDescriptions: { OWNER: "Full hotel access", ADMIN: "Manages hotel operations", USER: "Limited everyday access" }, permissions: { view: "View", create: "Create", edit: "Edit", delete: "Delete" }, modules: { dashboard: "Dashboard", departments: "Departments", teams: "Teams", users: "Users", activityLog: "Activity log", recycleBin: "Recycle bin" } },
  de: { title: "Rollen & Zugriffsrechte", roles: "Rollen", chooseRole: "Rolle zum Konfigurieren auswählen", configure: "Legen Sie fest, was diese Rolle tun darf", ownerLocked: "Der Eigentümer hat immer vollen Zugriff", module: "Modul", save: "Änderungen speichern", savedPreview: "UI-Änderungen für diese Vorschau gespeichert.", roleNames: { OWNER: "Eigentümer", ADMIN: "Administrator", USER: "Benutzer" }, roleDescriptions: { OWNER: "Vollständiger Hotelzugriff", ADMIN: "Verwaltet den Hotelbetrieb", USER: "Eingeschränkter täglicher Zugriff" }, permissions: { view: "Ansehen", create: "Erstellen", edit: "Bearbeiten", delete: "Löschen" }, modules: { dashboard: "Dashboard", departments: "Abteilungen", teams: "Teams", users: "Benutzer", activityLog: "Aktivitätsprotokoll", recycleBin: "Papierkorb" } },
  it: { title: "Ruoli e diritti di accesso", roles: "Ruoli", chooseRole: "Scegli un ruolo da configurare", configure: "Scegli cosa può fare questo ruolo", ownerLocked: "Il proprietario ha sempre accesso completo", module: "Modulo", save: "Salva modifiche", savedPreview: "Modifiche UI salvate per questa anteprima.", roleNames: { OWNER: "Proprietario", ADMIN: "Amministratore", USER: "Utente" }, roleDescriptions: { OWNER: "Accesso completo all'hotel", ADMIN: "Gestisce le operazioni dell'hotel", USER: "Accesso quotidiano limitato" }, permissions: { view: "Visualizza", create: "Crea", edit: "Modifica", delete: "Elimina" }, modules: { dashboard: "Dashboard", departments: "Reparti", teams: "Team", users: "Utenti", activityLog: "Registro attività", recycleBin: "Cestino" } },
} as const;

export const clientRoleMessages = {
  en: { settings: "Settings", title: "Roles & module access", description: "Controls which modules are visible in the sidebar for each role.", module: "Module", departments: "Departments", allDepartments: "All departments", levels: { employee: "Employee", teamLead: "Team/Department Lead", management: "Management", administrator: "Administrator" }, modules: { dashboard: "Dashboard", aiAssistant: "AI Assistant", handovers: "Handovers", tasks: "Tasks & Checklists", housekeeping: "Housekeeping", repairs: "Repairs", notes: "Notes", schedule: "Schedule", recruiting: "Recruiting", manuals: "Manuals", budget: "Budget & Forecast", revenue: "AI Revenue Forecast" }, departmentNames: { reception: "Reception", restaurant: "Restaurant/Service", housekeeping: "Housekeeping", maintenance: "Maintenance" } },
  de: { settings: "Einstellungen", title: "Rollen & Modul-Zugriff", description: "Steuert, welche Module in der Seitenleiste für welche Rolle sichtbar sind.", module: "Modul", departments: "Abteilungen", allDepartments: "Alle Abteilungen", levels: { employee: "Mitarbeiter", teamLead: "Team-/Abteilungsleitung", management: "Management", administrator: "Administrator" }, modules: { dashboard: "Dashboard", aiAssistant: "KI-Assistent", handovers: "Übergaben", tasks: "Aufgaben & Checklisten", housekeeping: "Housekeeping", repairs: "Reparaturen", notes: "Notizen", schedule: "Dienstplan", recruiting: "Recruiting", manuals: "Handbücher", budget: "Budget & Forecast", revenue: "AI Revenue Forecast" }, departmentNames: { reception: "Rezeption", restaurant: "Restaurant/Service", housekeeping: "Housekeeping", maintenance: "Haustechnik" } },
  it: { settings: "Impostazioni", title: "Ruoli e accesso ai moduli", description: "Controlla quali moduli sono visibili nella barra laterale per ciascun ruolo.", module: "Modulo", departments: "Reparti", allDepartments: "Tutti i reparti", levels: { employee: "Dipendente", teamLead: "Responsabile team/reparto", management: "Direzione", administrator: "Amministratore" }, modules: { dashboard: "Dashboard", aiAssistant: "Assistente IA", handovers: "Passaggi di consegne", tasks: "Attività e checklist", housekeeping: "Housekeeping", repairs: "Riparazioni", notes: "Note", schedule: "Turni", recruiting: "Selezione", manuals: "Manuali", budget: "Budget e previsioni", revenue: "Previsioni ricavi IA" }, departmentNames: { reception: "Reception", restaurant: "Ristorante/Servizio", housekeeping: "Housekeeping", maintenance: "Manutenzione" } },
} as const;

export const roleLevelNames = {
  en: { EMPLOYEE: "Employee", TEAM_LEAD: "Team/Department Lead", MANAGEMENT: "Management", ADMIN: "Administrator" },
  de: { EMPLOYEE: "Mitarbeiter", TEAM_LEAD: "Team-/Abteilungsleitung", MANAGEMENT: "Management", ADMIN: "Administrator" },
  it: { EMPLOYEE: "Dipendente", TEAM_LEAD: "Responsabile team/reparto", MANAGEMENT: "Direzione", ADMIN: "Amministratore" },
} as const;

export const additionalModuleMessages = {
  en: { chat: "Chat", mcp: "MCP", competitors: "Competitors", users: "Create & edit users", roles: "Roles & access rights" },
  de: { chat: "Chat", mcp: "MCP", competitors: "Wettbewerber", users: "Benutzer erstellen & bearbeiten", roles: "Rollen & Zugriffsrechte" },
  it: { chat: "Chat", mcp: "MCP", competitors: "Concorrenti", users: "Crea e modifica utenti", roles: "Ruoli e diritti di accesso" },
} as const;

export const userManagementMessages = {
  en: { settings: "Settings", search: "Search by name or email…", add: "Add user", employee: "Employee", email: "Email", department: "Department", role: "Role", status: "Status", actions: "Actions", active: "Active", inactive: "Inactive", noDepartment: "No department", empty: "No users found.", showing: "Showing {count} employees", createTitle: "Create user", editTitle: "Edit user", firstName: "First name", lastName: "Last name", phone: "Phone number (optional)", password: "Password", newPassword: "New password (optional)", save: "Save", cancel: "Cancel", required: "This field is required.", invalidEmail: "Enter a valid email address.", shortPassword: "Password must contain at least 8 characters.", emailExists: "This email address is already in use." },
  de: { settings: "Einstellungen", search: "Nach Name oder E-Mail suchen…", add: "Nutzer hinzufügen", employee: "Mitarbeiter", email: "E-Mail", department: "Abteilung", role: "Rolle", status: "Status", actions: "Aktionen", active: "Aktiv", inactive: "Inaktiv", noDepartment: "Keine Abteilung", empty: "Keine Benutzer gefunden.", showing: "Zeigt {count} Mitarbeiter", createTitle: "Benutzer erstellen", editTitle: "Benutzer bearbeiten", firstName: "Vorname", lastName: "Nachname", phone: "Telefonnummer (optional)", password: "Passwort", newPassword: "Neues Passwort (optional)", save: "Speichern", cancel: "Abbrechen", required: "Dieses Feld ist erforderlich.", invalidEmail: "Geben Sie eine gültige E-Mail-Adresse ein.", shortPassword: "Das Passwort muss mindestens 8 Zeichen enthalten.", emailExists: "Diese E-Mail-Adresse wird bereits verwendet." },
  it: { settings: "Impostazioni", search: "Cerca per nome o e-mail…", add: "Aggiungi utente", employee: "Dipendente", email: "E-mail", department: "Reparto", role: "Ruolo", status: "Stato", actions: "Azioni", active: "Attivo", inactive: "Inattivo", noDepartment: "Nessun reparto", empty: "Nessun utente trovato.", showing: "Mostra {count} dipendenti", createTitle: "Crea utente", editTitle: "Modifica utente", firstName: "Nome", lastName: "Cognome", phone: "Numero di telefono (facoltativo)", password: "Password", newPassword: "Nuova password (facoltativa)", save: "Salva", cancel: "Annulla", required: "Questo campo è obbligatorio.", invalidEmail: "Inserisci un indirizzo e-mail valido.", shortPassword: "La password deve contenere almeno 8 caratteri.", emailExists: "Questo indirizzo e-mail è già in uso." },
} as const;

export const moduleNavigationMessages = {
  en: { chat: "Chat", competitors: "Competitors", mcp: "MCP" },
  de: { chat: "Chat", competitors: "Wettbewerber", mcp: "MCP" },
  it: { chat: "Chat", competitors: "Concorrenti", mcp: "MCP" },
} as const;

export const mcpSettingsMessages = {
  en: { title: "MCP integrations", description: "Connect and manage MCP services" },
  de: { title: "MCP-Integrationen", description: "MCP-Dienste verbinden und verwalten" },
  it: { title: "Integrazioni MCP", description: "Collega e gestisci i servizi MCP" },
} as const;
