"use client";
import { useCallback,useEffect,useMemo,useState,type FormEvent,type ReactNode } from "react";
import { useRouter } from "next/navigation";
import { AppShell } from "../../../components/dashboard/app-shell";
import { BrandLoader } from "../../../components/ui/brand-loader";
import { Button } from "../../../components/ui/button";
import { Input } from "../../../components/ui/input";
import { PasswordInput } from "../../../components/ui/password-input";
import { useI18n } from "../../../components/i18n/i18n-provider";
import { requestMessages,roleLevelNames,userManagementMessages } from "../../../lib/i18n/dictionaries";
type Role="EMPLOYEE"|"TEAM_LEAD"|"MANAGEMENT"|"ADMIN";
type User={id:string;first_name:string;last_name:string;email:string;phone_number:string|null;role:Role;is_active:boolean;department_id:string|null;department_en:string|null;department_de:string|null;department_it:string|null};
type Department={id:string;name_en:string;name_de:string;name_it:string};
type Form={firstName:string;lastName:string;email:string;phone:string;password:string;role:Role;departmentId:string;isActive:boolean};
const blank:Form={firstName:"",lastName:"",email:"",phone:"",password:"",role:"EMPLOYEE",departmentId:"",isActive:true};
export default function UsersPage(){
 const{locale}=useI18n();const router=useRouter();const t=userManagementMessages[locale];const req=requestMessages[locale];
 const[users,setUsers]=useState<User[]>([]),[departments,setDepartments]=useState<Department[]>([]);const[currentId,setCurrentId]=useState("");const[search,setSearch]=useState("");const[loading,setLoading]=useState(true),[busy,setBusy]=useState(false);const[error,setError]=useState("");const[editing,setEditing]=useState<User|null|undefined>();const[form,setForm]=useState<Form>(blank);const[errors,setErrors]=useState<Partial<Record<keyof Form,string>>>({});
 const load=useCallback(async()=>{const r=await fetch("/api/settings/users");if(r.status===401)return router.replace("/login");if(!r.ok)throw new Error();const d=await r.json();setUsers(d.users);setDepartments(d.departments);setCurrentId(d.currentUserId);},[router]);
 useEffect(()=>{let active=true;Promise.resolve().then(()=>load()).catch(()=>active&&setError(req.failed)).finally(()=>active&&setLoading(false));return()=>{active=false}},[load,req.failed]);
 const shown=useMemo(()=>{const q=search.toLowerCase().trim();return q?users.filter(u=>`${u.first_name} ${u.last_name} ${u.email}`.toLowerCase().includes(q)):users},[search,users]);
 function open(u?:User){setEditing(u??null);setError("");setErrors({});setForm(u?{firstName:u.first_name,lastName:u.last_name,email:u.email,phone:u.phone_number??"",password:"",role:u.role,departmentId:u.department_id??"",isActive:u.is_active}:blank)}
 async function save(e:FormEvent){e.preventDefault();const x:typeof errors={};if(!form.firstName.trim())x.firstName=t.required;if(!form.lastName.trim())x.lastName=t.required;if(!/^\S+@\S+\.\S+$/.test(form.email))x.email=t.invalidEmail;if((!editing||form.password)&&form.password.length<8)x.password=t.shortPassword;if(Object.keys(x).length)return setErrors(x);setBusy(true);setError("");try{const r=await fetch(editing?`/api/settings/users/${editing.id}`:"/api/settings/users",{method:editing?"PATCH":"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(form)});const d=await r.json();if(!r.ok)throw new Error(d.error);await load();setEditing(undefined)}catch(e){setError(e instanceof Error&&e.message==="EMAIL_EXISTS"?t.emailExists:req.failed)}finally{setBusy(false)}}
 async function remove(u:User){setBusy(true);try{const r=await fetch(`/api/settings/users/${u.id}`,{method:"DELETE"});if(!r.ok)throw new Error();setUsers(v=>v.filter(i=>i.id!==u.id))}catch{setError(req.failed)}finally{setBusy(false)}}
 const dept=(u:User)=>u[locale==="de"?"department_de":locale==="it"?"department_it":"department_en"]??t.noDepartment;const roles:Role[]=["EMPLOYEE","TEAM_LEAD","MANAGEMENT","ADMIN"];
 return <AppShell activeItem="settings"><main className="p-4 sm:p-5 lg:p-7"><button onClick={()=>router.push("/settings")} className="mb-3.5 cursor-pointer text-[12.5px] font-semibold text-[var(--qf-text-muted)]">← {t.settings}</button>{error&&editing===undefined?<p className="mb-4 rounded-md bg-red-50 p-3 text-xs text-red-700">{error}</p>:null}{loading?<BrandLoader label={req.loading}/>:<><div className="mb-4 flex gap-2"><input value={search} onChange={e=>setSearch(e.target.value)} placeholder={t.search} className="h-10 flex-1 rounded-lg border border-[var(--qf-border)] px-3.5 text-sm outline-none focus:border-[var(--qf-accent)]"/><Button onClick={()=>open()}>+ {t.add}</Button></div><div className="overflow-x-auto rounded-[var(--qf-radius)] border border-[var(--qf-border)] bg-white"><table className="w-full min-w-[820px]"><thead><tr className="bg-[#f9f8f6] text-left text-[11px] text-[var(--qf-text-muted)]">{[t.employee,t.email,t.department,t.role,t.status,t.actions].map((h,i)=><th key={h} className={`border-b-2 border-[var(--qf-border)] px-4 py-3 ${i===5?"text-right":""}`}>{h}</th>)}</tr></thead><tbody>{shown.map(u=><tr key={u.id} className="hover:bg-[#fafaf8]"><Cell><div className="flex items-center gap-2"><span className="flex h-8 w-8 items-center justify-center rounded-full bg-[var(--qf-accent-soft)] text-[11px] font-bold">{u.first_name[0]}{u.last_name[0]}</span><b className="text-[13px]">{u.first_name} {u.last_name}</b></div></Cell><Cell>{u.email}</Cell><Cell>{dept(u)}</Cell><Cell><span className="rounded-full bg-[var(--qf-accent-soft)] px-2 py-1 text-[10px] font-bold">{roleLevelNames[locale][u.role]}</span></Cell><Cell><span className={`rounded-full px-2 py-1 text-[10px] font-bold ${u.is_active?"bg-green-100 text-green-700":"bg-gray-100 text-gray-500"}`}>{u.is_active?t.active:t.inactive}</span></Cell><Cell right><button onClick={()=>open(u)} className="mr-1.5 h-7 w-7 cursor-pointer rounded-md border border-[var(--qf-border)]">✏️</button><button disabled={u.id===currentId} onClick={()=>void remove(u)} className="h-7 w-7 cursor-pointer rounded-md border border-[var(--qf-border)] disabled:opacity-30">🗑️</button></Cell></tr>)}</tbody></table>{shown.length===0?<p className="p-8 text-center text-sm text-[var(--qf-text-muted)]">{t.empty}</p>:null}</div><p className="mt-2 text-xs text-[var(--qf-text-light)]">{t.showing.replace("{count}",String(shown.length))}</p></>}
 {editing!==undefined?<div className="fixed inset-0 z-[100] flex items-center justify-center bg-black/45 p-4" onMouseDown={e=>e.target===e.currentTarget&&setEditing(undefined)}><div className="max-h-[90vh] w-full max-w-[620px] overflow-y-auto rounded-xl bg-white"><header className="flex justify-between border-b border-[var(--qf-border)] px-5 py-4"><b>{editing?t.editTitle:t.createTitle}</b><button onClick={()=>setEditing(undefined)}>×</button></header><form onSubmit={save} noValidate><div className="grid gap-4 p-5 sm:grid-cols-2">{error?<p className="text-xs text-red-600 sm:col-span-2">{error}</p>:null}<Input label={t.firstName} value={form.firstName} error={errors.firstName} onChange={e=>setForm({...form,firstName:e.target.value})}/><Input label={t.lastName} value={form.lastName} error={errors.lastName} onChange={e=>setForm({...form,lastName:e.target.value})}/><div className="sm:col-span-2"><Input type="email" label={t.email} value={form.email} error={errors.email} onChange={e=>setForm({...form,email:e.target.value})}/></div><Input label={t.phone} value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})}/><PasswordInput label={editing?t.newPassword:t.password} value={form.password} error={errors.password} onChange={e=>setForm({...form,password:e.target.value})}/><Select label={t.role} value={form.role} change={v=>setForm({...form,role:v as Role})}>{roles.map(r=><option key={r} value={r}>{roleLevelNames[locale][r]}</option>)}</Select><Select label={t.department} value={form.departmentId} change={v=>setForm({...form,departmentId:v})}><option value="">{t.noDepartment}</option>{departments.map(d=><option key={d.id} value={d.id}>{d[locale==="de"?"name_de":locale==="it"?"name_it":"name_en"]}</option>)}</Select><div className="sm:col-span-2"><Select label={t.status} value={form.isActive?"active":"inactive"} change={v=>setForm({...form,isActive:v==="active"})}><option value="active">{t.active}</option><option value="inactive">{t.inactive}</option></Select></div></div><footer className="flex justify-end gap-2 border-t border-[var(--qf-border)] p-4"><Button type="button" variant="secondary" onClick={()=>setEditing(undefined)}>{t.cancel}</Button><Button type="submit">{t.save}</Button></footer></form></div></div>:null}{busy?<BrandLoader label={req.loading} overlay/>:null}</main></AppShell>}
function Cell({children,right=false}:{children:ReactNode;right?:boolean}){return <td className={`border-b border-[var(--qf-border)] px-4 py-3 text-xs ${right?"text-right":""}`}>{children}</td>}
function Select({label,value,change,children}:{label:string;value:string;change:(v:string)=>void;children:ReactNode}){return <label className="text-[13px] font-semibold"><span className="mb-1.5 block">{label}</span><select value={value} onChange={e=>change(e.target.value)} className="h-11 w-full rounded-lg border border-[var(--qf-border)] bg-white px-3">{children}</select></label>}
