export type JobIconCat =
  | "work" | "people" | "pay" | "time" | "place" | "tools" | "learn" | "health" | "status" | "more";

export const JOB_ICON_CATS: JobIconCat[] = ["work", "people", "pay", "time", "place", "tools", "learn", "health", "status", "more"];

export type JobIcon = { glyph: string; tags: string };

/** Icons used in job / recruiting pages — searchable by tags. */
export const JOB_ICONS: Record<JobIconCat, JobIcon[]> = {
  work: [
    { glyph: "💼", tags: "briefcase job work office career" },
    { glyph: "👔", tags: "tie suit professional formal" },
    { glyph: "🏢", tags: "office building company" },
    { glyph: "🏭", tags: "factory industry production" },
    { glyph: "🏗️", tags: "construction building site" },
    { glyph: "🧑‍🍳", tags: "chef cook kitchen gastronomy" },
    { glyph: "👨‍🍳", tags: "chef cook kitchen" },
    { glyph: "👩‍🍳", tags: "chef cook kitchen" },
    { glyph: "🧹", tags: "cleaning housekeeping maid" },
    { glyph: "🛏️", tags: "bed housekeeping hotel room" },
    { glyph: "🛎️", tags: "bellhop reception hotel service" },
    { glyph: "🔑", tags: "key reception rooms" },
    { glyph: "🏨", tags: "hotel hospitality" },
    { glyph: "🍽️", tags: "restaurant dining service" },
    { glyph: "🥂", tags: "bar waiter hospitality" },
    { glyph: "☕", tags: "coffee cafe barista" },
    { glyph: "🧁", tags: "pastry bakery kitchen" },
    { glyph: "🛠️", tags: "maintenance repair technician" },
    { glyph: "🔧", tags: "wrench tools technician" },
    { glyph: "⚙️", tags: "gear settings technical" },
    { glyph: "💻", tags: "laptop computer office it" },
    { glyph: "🖥️", tags: "desktop computer office" },
    { glyph: "⌨️", tags: "keyboard office it" },
    { glyph: "🖱️", tags: "mouse office" },
    { glyph: "📞", tags: "phone reception call center" },
    { glyph: "☎️", tags: "telephone reception" },
    { glyph: "📧", tags: "email office" },
    { glyph: "📝", tags: "notes writing administration" },
    { glyph: "📋", tags: "clipboard checklist tasks" },
    { glyph: "📂", tags: "folder files admin" },
    { glyph: "📦", tags: "box warehouse logistics" },
    { glyph: "🚚", tags: "truck delivery logistics driver" },
    { glyph: "🚗", tags: "car driver transport" },
    { glyph: "🚌", tags: "bus driver transport" },
    { glyph: "✈️", tags: "plane travel tourism" },
    { glyph: "🛳️", tags: "ship cruise hospitality" },
    { glyph: "🧑‍💼", tags: "office worker employee" },
    { glyph: "👨‍💼", tags: "office man manager" },
    { glyph: "👩‍💼", tags: "office woman manager" },
    { glyph: "🧑‍🔧", tags: "mechanic technician" },
    { glyph: "🧑‍🌾", tags: "farmer garden grounds" },
    { glyph: "🧑‍⚕️", tags: "medical health spa wellness" },
    { glyph: "💇", tags: "hair spa wellness" },
    { glyph: "🧖", tags: "spa wellness sauna" },
    { glyph: "🏋️", tags: "gym fitness trainer" },
    { glyph: "🎯", tags: "target goals performance" },
    { glyph: "📈", tags: "growth career chart" },
    { glyph: "📊", tags: "chart data analytics" },
    { glyph: "🪪", tags: "id badge employee card" },
    { glyph: "📌", tags: "pin notice board" },
  ],
  people: [
    { glyph: "😊", tags: "smile happy friendly" },
    { glyph: "😄", tags: "grin happy" },
    { glyph: "😁", tags: "beaming happy" },
    { glyph: "🙂", tags: "slight smile" },
    { glyph: "😉", tags: "wink friendly" },
    { glyph: "🤗", tags: "hug welcome" },
    { glyph: "🙋", tags: "raising hand apply volunteer" },
    { glyph: "👋", tags: "wave hello welcome" },
    { glyph: "🤝", tags: "handshake team deal" },
    { glyph: "👍", tags: "thumbs up yes" },
    { glyph: "👎", tags: "thumbs down no" },
    { glyph: "👏", tags: "clap praise" },
    { glyph: "💪", tags: "strong muscle effort" },
    { glyph: "🧠", tags: "brain smart thinking" },
    { glyph: "👀", tags: "eyes look attention" },
    { glyph: "🧑", tags: "person" },
    { glyph: "👨", tags: "man" },
    { glyph: "👩", tags: "woman" },
    { glyph: "🧑‍🤝‍🧑", tags: "people pair colleagues" },
    { glyph: "👥", tags: "busts team people" },
    { glyph: "👨‍👩‍👧‍👦", tags: "family" },
    { glyph: "🧓", tags: "older person" },
    { glyph: "👶", tags: "baby family" },
    { glyph: "🗣️", tags: "speaking speak" },
    { glyph: "💬", tags: "speech talk communication" },
  ],
  pay: [
    { glyph: "💰", tags: "money bag salary pay" },
    { glyph: "💵", tags: "dollar cash salary" },
    { glyph: "💶", tags: "euro cash salary" },
    { glyph: "💷", tags: "pound cash" },
    { glyph: "💴", tags: "yen cash" },
    { glyph: "💸", tags: "money flying pay" },
    { glyph: "💳", tags: "card payment" },
    { glyph: "🏦", tags: "bank finance" },
    { glyph: "💎", tags: "gem bonus quality" },
    { glyph: "🏆", tags: "trophy award bonus" },
    { glyph: "🥇", tags: "gold medal best" },
    { glyph: "🥈", tags: "silver medal" },
    { glyph: "🥉", tags: "bronze medal" },
    { glyph: "🎁", tags: "gift bonus perk" },
    { glyph: "🎄", tags: "christmas bonus" },
    { glyph: "🏖️", tags: "holiday vacation bonus" },
    { glyph: "☂️", tags: "umbrella benefits insurance" },
    { glyph: "🛡️", tags: "shield stable secure benefits" },
    { glyph: "📈", tags: "raise growth salary" },
    { glyph: "🪙", tags: "coin money" },
  ],
  time: [
    { glyph: "⏰", tags: "alarm clock time hours" },
    { glyph: "🕒", tags: "clock time" },
    { glyph: "🕓", tags: "clock afternoon" },
    { glyph: "🕕", tags: "clock evening" },
    { glyph: "🕙", tags: "clock morning" },
    { glyph: "🕛", tags: "clock noon" },
    { glyph: "⏱️", tags: "stopwatch duration" },
    { glyph: "⏳", tags: "hourglass wait later" },
    { glyph: "⌛", tags: "hourglass done" },
    { glyph: "📅", tags: "calendar date start" },
    { glyph: "🗓️", tags: "calendar planner" },
    { glyph: "📆", tags: "tear calendar date" },
    { glyph: "🌙", tags: "night shift" },
    { glyph: "☀️", tags: "day shift sun" },
    { glyph: "🌅", tags: "sunrise morning early" },
    { glyph: "🌇", tags: "sunset evening" },
    { glyph: "🚀", tags: "start immediately rocket" },
    { glyph: "⚡", tags: "fast immediately" },
    { glyph: "🔜", tags: "soon next" },
  ],
  place: [
    { glyph: "📍", tags: "pin location city" },
    { glyph: "📌", tags: "pushpin location" },
    { glyph: "🗺️", tags: "map area region" },
    { glyph: "🌍", tags: "globe world international" },
    { glyph: "🏠", tags: "home house local" },
    { glyph: "🏡", tags: "house garden home" },
    { glyph: "🏘️", tags: "houses neighborhood" },
    { glyph: "🏙️", tags: "city skyline" },
    { glyph: "⛰️", tags: "mountain region alpine" },
    { glyph: "🌲", tags: "nature forest region" },
    { glyph: "🌊", tags: "sea lake water" },
    { glyph: "🚉", tags: "station commute train" },
    { glyph: "🅿️", tags: "parking" },
    { glyph: "🚲", tags: "bike commute" },
    { glyph: "🚶", tags: "walk commute" },
  ],
  tools: [
    { glyph: "🧰", tags: "toolbox tools" },
    { glyph: "🔨", tags: "hammer tools" },
    { glyph: "🪛", tags: "screwdriver tools" },
    { glyph: "🪚", tags: "saw carpenter" },
    { glyph: "🔩", tags: "nut bolt technical" },
    { glyph: "⚖️", tags: "scale legal fairness" },
    { glyph: "🔒", tags: "lock security" },
    { glyph: "🧯", tags: "extinguisher safety" },
    { glyph: "🦺", tags: "safety vest clothing" },
    { glyph: "🪖", tags: "helmet safety" },
    { glyph: "🧤", tags: "gloves safety" },
    { glyph: "🥽", tags: "goggles safety" },
    { glyph: "👟", tags: "shoes uniform" },
    { glyph: "👗", tags: "dress uniform" },
    { glyph: "👕", tags: "shirt uniform" },
    { glyph: "📱", tags: "phone mobile" },
    { glyph: "🎧", tags: "headset support" },
    { glyph: "🎥", tags: "camera video" },
    { glyph: "📸", tags: "photo camera" },
    { glyph: "🖨️", tags: "printer office" },
  ],
  learn: [
    { glyph: "📚", tags: "books learn training" },
    { glyph: "📖", tags: "book read learn" },
    { glyph: "🎓", tags: "graduation education" },
    { glyph: "✏️", tags: "pencil write" },
    { glyph: "🖊️", tags: "pen write" },
    { glyph: "💡", tags: "idea light creative" },
    { glyph: "✨", tags: "sparkles creative" },
    { glyph: "🌱", tags: "seedling junior start grow" },
    { glyph: "🌿", tags: "herb grow experience" },
    { glyph: "🌳", tags: "tree senior experience" },
    { glyph: "⭐", tags: "star expert" },
    { glyph: "🌟", tags: "glowing star talent" },
    { glyph: "🔍", tags: "search find" },
    { glyph: "🧭", tags: "compass direction career" },
    { glyph: "🧩", tags: "puzzle problem solving" },
  ],
  health: [
    { glyph: "❤️", tags: "heart health care" },
    { glyph: "💚", tags: "green heart health" },
    { glyph: "💙", tags: "blue heart trust" },
    { glyph: "💛", tags: "yellow heart" },
    { glyph: "🧡", tags: "orange heart" },
    { glyph: "🩺", tags: "stethoscope medical" },
    { glyph: "💊", tags: "pill health insurance" },
    { glyph: "🏥", tags: "hospital medical" },
    { glyph: "🧘", tags: "yoga wellness balance" },
    { glyph: "🍎", tags: "apple health food" },
    { glyph: "🥗", tags: "salad staff meal" },
    { glyph: "😴", tags: "sleep rest recovery" },
  ],
  status: [
    { glyph: "✅", tags: "check yes success" },
    { glyph: "❌", tags: "cross no fail" },
    { glyph: "✔️", tags: "check mark yes" },
    { glyph: "☑️", tags: "ballot check" },
    { glyph: "➕", tags: "plus add" },
    { glyph: "➖", tags: "minus" },
    { glyph: "❓", tags: "question" },
    { glyph: "❗", tags: "exclamation important" },
    { glyph: "ℹ️", tags: "info" },
    { glyph: "⚠️", tags: "warning" },
    { glyph: "🚫", tags: "forbidden no" },
    { glyph: "🆗", tags: "ok" },
    { glyph: "🆕", tags: "new" },
    { glyph: "🆓", tags: "free" },
    { glyph: "➡️", tags: "arrow next" },
    { glyph: "⬅️", tags: "arrow back" },
    { glyph: "⬆️", tags: "arrow up" },
    { glyph: "⬇️", tags: "arrow down" },
    { glyph: "✔️", tags: "done" },
  ],
  more: [
    { glyph: "🎉", tags: "party celebrate events" },
    { glyph: "🎊", tags: "confetti events" },
    { glyph: "🎈", tags: "balloon fun" },
    { glyph: "🎵", tags: "music" },
    { glyph: "🎶", tags: "notes music" },
    { glyph: "🎤", tags: "mic voice" },
    { glyph: "🎬", tags: "clapper video" },
    { glyph: "🌞", tags: "sun weather" },
    { glyph: "❄️", tags: "snow winter season" },
    { glyph: "🌸", tags: "blossom spring" },
    { glyph: "🍀", tags: "clover luck" },
    { glyph: "🌈", tags: "rainbow diversity" },
    { glyph: "🐶", tags: "dog pet friendly" },
    { glyph: "🐱", tags: "cat pet friendly" },
    { glyph: "☕", tags: "coffee break" },
    { glyph: "🍕", tags: "pizza team food" },
    { glyph: "🎂", tags: "cake birthday" },
    { glyph: "🚗", tags: "car" },
    { glyph: "🔥", tags: "fire hot popular" },
    { glyph: "💯", tags: "hundred perfect" },
    { glyph: "🔔", tags: "bell notify" },
    { glyph: "📣", tags: "megaphone announce" },
    { glyph: "🏷️", tags: "label tag" },
    { glyph: "📎", tags: "paperclip file" },
    { glyph: "🔗", tags: "link" },
    { glyph: "🖼️", tags: "picture image" },
    { glyph: "📄", tags: "page document cv" },
    { glyph: "📨", tags: "incoming envelope" },
    { glyph: "✉️", tags: "envelope mail" },
    { glyph: "🔏", tags: "privacy lock" },
  ],
};

export function allJobIcons(): JobIcon[] {
  const seen = new Set<string>();
  const list: JobIcon[] = [];
  for (const cat of JOB_ICON_CATS) {
    for (const icon of JOB_ICONS[cat]) {
      if (seen.has(icon.glyph)) continue;
      seen.add(icon.glyph);
      list.push(icon);
    }
  }
  return list;
}
